### ISSUE TITLE
[New Discover Tab] Update the Discover tab header

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1002]
Given that I am a user of nos
When I arrive on the Discover tab
Then I should see the following in the header 

Hamburger Menu | Discover | i icon
Full width search bar w/ the following helper text: Search people in Nostr or the Fediverse
Horizontal scroll categories:
New | Journalists | Tech | Art | Environment | Sports | Gaming | Music

Designs: 
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732%3A1749&mode=design&t=dQI79RcEBZQsYyRK-1

**Comment by joshuatbrown** [comment]
@setch-l for this ticket, could we change the scope slightly? I'd like to exclude the horizontal scroll categories until we do #1024. This way, we can do both the UI and the functionality for the categories at the same time so everything continues to work as expected in the Discover tab. I'd like to avoid having categories that don't actually do anything (even if the builds are only used internally).

**Comment by setch-l** [comment]
@joshuatbrown - Sure that works
