### ISSUE TITLE
[New Discover Tab] Create profile cards for the Discover tab

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1004]
Given that I am a user of Nos
When I view the Discover tab
I want to see profile information for people to follow 

AC
Each card should have the following info: 
Profile Image + Follow icon (w/ 40 x 40 click space) 
NIP05
Bio
Followed by people you know (only if available) 
This design can be used for search results and mentions search results

Designs: 
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732%3A1749&mode=design&t=UNPwfKdniTIwhZjs-1

**Comment by joshuatbrown** [comment]
@Chardot I'm not able to export icons from Figma. Can you provide SVG versions of the follow and unfollow buttons (or better yet, enable exporting for me in Figma)?

**Comment by Chardot** [comment]
> [@Chardot](https://github.com/Chardot) I'm not able to export icons from Figma. Can you provide SVG versions of the follow and unfollow buttons (or better yet, enable exporting for me in Figma)?

Here are the icons in PNG, exported in sizes 1, 2 and 3x.

[icons_follow-following-SM.zip](https://github.com/planetary-social/nos/files/15001400/icons_follow-following-SM.zip)

I'll investigate what's preventing you from exporting on Figma.

**Comment by Chardot** [comment]
@joshuatbrown Also remember this:

![Image](https://github.com/planetary-social/nos/assets/477835/acd943cb-4836-462d-afaf-8617370fa92a)

![Image](https://github.com/planetary-social/nos/assets/477835/b1461a2d-11ba-44c7-853d-faccd45d7088)

**Comment by joshuatbrown** [comment]
@Chardot currently we show "Muted" on the trailing edge when a user is muted. Should we keep this here or move it? I can't find it in the design.

![Image](https://github.com/planetary-social/nos/assets/59564/c35347a7-0c43-4c7d-b6ae-5969349260f6)

**Comment by joshuatbrown** [comment]
@Chardot could you send the icons as SVG instead of PNG? That's [Apple's recommended approach](https://developer.apple.com/design/human-interface-guidelines/icons) now:

> If you create a custom interface icon, use a vector format like PDF or SVG.

**Comment by Chardot** [comment]
> @Chardot could you send the icons as SVG instead of PNG? That's [Apple's recommended approach](https://developer.apple.com/design/human-interface-guidelines/icons) now:
> 
> > If you create a custom interface icon, use a vector format like PDF or SVG.

Sure! I'll share the SVG in a minute

**Comment by Chardot** [comment]
> @Chardot could you send the icons as SVG instead of PNG? That's [Apple's recommended approach](https://developer.apple.com/design/human-interface-guidelines/icons) now:
> 
> > If you create a custom interface icon, use a vector format like PDF or SVG.

Here's the Zip with the SVG icons: 
[icons_Follow-Following-SM.zip](https://github.com/planetary-social/nos/files/15012353/icons_Follow-Following-SM.zip)

**Comment by joshuatbrown** [comment]
@Chardot thanks for the SVGs! Here's the current "Muted" indicator:

![Image](https://github.com/planetary-social/nos/assets/59564/5c3c5ccb-2892-4d8f-841d-a353c27d111b)

**Comment by joshuatbrown** [comment]
@setch-l if we're unsure about it (and I think I am, too), I suggest we leave the "Muted" text for now and deal with this later. Seems like a small thing we don't need to worry about right now.

**Comment by joshuatbrown** [comment]
Oh, and the thing about leaving the "Muted" text is that it's already done, which means we can close this ticket sooner.

**Comment by mplorentz** [comment]
@setch-l it's also not hard to make a change and have the new design only apply to the discover cards. We still have the old code and we can just put it back in place for search results and mentions.

**Comment by joshuatbrown** [comment]
@setch-l reusing the existing profile cards that show up in search results was the quickest way to get the profile cards for the Discover tab. I'm not sure we've lost much here, as @mplorentz points out.
