### ISSUE TITLE
[New Discover Tab] Clicking the rest of the profile card opens the profile

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1006]
Given that I am a user of nos 
When I click on a profile card on the Discover page
Then the profile for that user should open.

**Comment by joshuatbrown** [comment]
From @mplorentz: there may be some code we can reuse from Planetary for the Discover tab, so this is my reminder to check on that before starting on this.

**Comment by mplorentz** [comment]
Looking at it in more detail now the style doesn't match as closely as I thought, but maybe it's still useful: https://github.com/planetary-social/planetary-ios/blob/main/Source/UI/Search/SearchResultsTab.swift

**Comment by joshuatbrown** [comment]
@setch-l there's not really anything to do on the development side for this since I used the existing profile card. I'll move this along with #1004, but maybe we just want to close/delete.
