### ISSUE TITLE
[Moderation hot fix] Clicking flag this content opens a menu

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1012]
Given that I am a user of Nos
When I click on "Flag this content" from the 3 dots menu
Then a second menu opens with the following content:

Header: Create a content flag for this post that other users in the network can see
Spam

Sexual Content
Nudity or pornography

Anti-social behavior
Trolling, harassment, or intolerance

Illegal
Content that violates the law in your country, CSAM, etc. 

Other
Items not included above 

Cancel option 

Designs:
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6068%3A3147&mode=design&t=HEHtN12NGQmL0d1s-1

**Comment by dcadenas** [comment]
@setch-l How should we map these categories to the [list of available options](https://raw.githubusercontent.com/planetary-social/cleanstr/main/src/lib/openAICategories.js)? Keep in mind that we are tied to nip-56 for top level categories and to nip-69 for specifics (we could skip nip-69 details though) 

Some are clear:

`Spam -> nip-56 spam`
`Sexual Content -> nip-56 nudity ? (but the content could be sexual with no nudity)`
`Anti-social behavior -> ????`
`Illegal -> nip-56 illegal`
`Other -> nip-56 other`

In these proposed mapping I didn't use a single nip-69

**Comment by Chardot** [comment]
@setch-l After our discussion with @dcadenas on Slack about the referenced design not being feasible, I updated the Figma frames with a new "Essential Action Sheet" frame, and this is the new URL: https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6068%3A3147&mode=design&t=HEHtN12NGQmL0d1s-1

**Comment by setch-l** [comment]
@dcadenas - Let's update the categories listed in the menu as follows: 

Spam = nip-56 spam 

Nudity or Sexual Content = nip56 nudity

Harassment or Intolerance = Profanity nip56 

Illegal = Illegal nip56 

Other = Other

**Comment by setch-l** [comment]
@dcadenas - The categories should be: 

Spam
Sexual Content 
Anti Social Behavior
Illegal 
Other 

But what I'm seeing instead is the following: 


![Image](https://github.com/planetary-social/nos/assets/6765558/68eb2294-b74d-4eee-8b60-3ea11a47daa9)

**Comment by dcadenas** [comment]
@setch-l I think you are not in staging, I see them correctly. Also keep in mind we changed this here: https://github.com/planetary-social/nos/pull/1063#discussion_r1578248744 maybe we missed your feedback on it?
