### ISSUE TITLE
[Moderation hot fix] Clicking post publicly displays the confirmation modal

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1014]
Given that I am a user of Nos
When I choose to post publicly 
Then I should see the existing confirmation modal in the app

See screenshot

![Image](https://github.com/planetary-social/nos/assets/6765558/b724705a-6e5a-49ae-9185-7c91f30f1962)

**Comment by dcadenas** [comment]
@setch-l do we ask for confirmation in the `Send to Nos` path ? in the local branch I'm working on I added this, but I'm not sure if we should (and of course the copy is ugly and needs some passes):


![Image](https://github.com/planetary-social/nos/assets/18184/62d99564-35e4-40d3-9607-b7fb5d9ef781)
