### ISSUE TITLE
[New Discover Tab] Test content

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1024]
Change the layout of the discover tab to match the new design: https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732-1749&mode=dev

Additionally, for the implementation and early release of the Discover tab, please include the following profiles in the following categories:

All | New | Journalists | Tech | Art | Environment | Sports | Gaming | Music 

All 
Include all of them in the default landing screen. 

New
npub1asuq0pxedwfagpqkdf4lrfmcyfaffgptmayel9947j8krad3x58srs20ap

Journalists 
npub1d9nndmy3lx6f00cysrmn2v9t6hz280uwycw0kgcfdhvg99azry8sududfv
npub1grz7afdguc67jkjly6fu0xmw0r386t8mtxafutu9u34dy207nt9ql335cv

Tech
npub1grz7afdguc67jkjly6fu0xmw0r386t8mtxafutu9u34dy207nt9ql335cv
npub1d9nndmy3lx6f00cysrmn2v9t6hz280uwycw0kgcfdhvg99azry8sududfv
npub1yxzkmtuyctjw2pffp6e9uvyrkp29hrqra2tm3xp3z9707z06muxsg75qvv

Art
npub1d7ggne0xsy8e2999q8cyh9zxda688axm07cwncufjeku0nahvfgsyz6qzr
npub17a49ajzjlwjv4znh85jcfgmk7qq5ck8m5advx66rudz8g0v034kss2hnk3
npub1l9kr6ajfwp6vfjp60vuzxwqwwlw884dff98a9cznujs520shsf9s35xfwh

Environment
npub1uh8e4y97tvs5zhsq6srr43qy0u66zk8xfy08xcrhef2803sdfcrslq62el

Sports
npub1aylzctp5p20yc842qfpu2w9j8q0kpqcfx8q3p42ugnp3t8uxg3xq3k8nn0

Music
npub1asuq0pxedwfagpqkdf4lrfmcyfaffgptmayel9947j8krad3x58srs20ap

**Comment by joshuatbrown** [comment]
I don't think I see a ticket to change the layout of the discover tab to match the new design, but we can just include that work in this ticket, unless we want to create a new one for that. Currently the Discover tab shows notes in multiple columns; we need to make it show profiles in a single column.

**Comment by joshuatbrown** [comment]
@setch-l @Chardot are we planning to have the categories scroll horizontally? See attached screenshot, where it's impossible to tell there are more categories after Environment.

![Image](https://github.com/planetary-social/nos/assets/59564/d8a8f979-7edc-428e-aaeb-afa1c591b799)

**Comment by joshuatbrown** [comment]
@setch-l @Chardot I found the answer in #1022, which says you can scroll to see other categories, but I'd still like to discuss my concern about discoverability of the other categories.

**Comment by Chardot** [comment]
> @setch-l @Chardot I found the answer in #1022, which says you can scroll to see other categories, but I'd still like to discuss my concern about discoverability of the other categories.

@joshuatbrown I share your concern and think it could be addressed in different ways: there could be an overlay to the right end of the Categories row, with a tappable element like a button with an arrow, that could work as a hint that there are more items to see to the right, and also scroll for you if you tap on it.

Another way would be to display a tooltip telling users that they can scroll to the right to explore more categories. Another one is to animate a horizontal scrolling motion when users first open this screen, so that they know of that functionality.

After discussing this with @setch-l yesterday we decided to go with the simplest approach for now which is not adding any extra functionality for this and let user testers try this to see how they react.

**Comment by joshuatbrown** [comment]
@setch-l the screenshot is in one of my comments above. Based on @Chardot's response, I'm good with leaving it as-is for now and seeing what happens.

**Comment by setch-l** [comment]
Hi @joshuatbrown - A couple of things on this page: 
- On the Mac - the scrollable navigation is aligned left. I'm not sure what the solution if any is for this... (it's not a deal breaker, just not pretty) 
- We discussed earlier today right aligning the profile icons to the edge of the Profile image above. 
- When I log in with a user who does not follow these accounts and doesn't follow much of anyone. The Discover tab is mostly empty - see video. 


https://github.com/planetary-social/nos/assets/6765558/146088dc-4160-45f6-892d-53a440790c7b
