### ISSUE TITLE
[New Discover Tab] Clicking on the i icon opens the tool tip

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1025]
Given that I am a user of the Nos Discover tab
When I click on the i icon
Then I should see a tool tip with the following message: 

Title: How is Discover populated? 
Body: Accounts on this tab are participants in the Nos Residency & Accelerator programs. 

Designs:
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5756%3A55&mode=design&t=dQI79RcEBZQsYyRK-1

**Comment by joshuatbrown** [comment]
@setch-l @Chardot could we consider using a built-in solution like Apple's [TipKit](https://developer.apple.com/documentation/tipkit/highlightingappfeatureswithtipkit?ref=createwithswift.com) rather than creating a custom popover? I'm concerned about the effort required to build the custom tip view, and TipKit could give us something close:

![Image](https://github.com/planetary-social/nos/assets/59564/2332cb6d-96db-4f05-8de5-c42d6d065ed6)

If so, we can look into what customization options we have -- I know for sure we can customize the text sizes and colors as I've done above.

**Comment by Chardot** [comment]
> @setch-l @Chardot could we consider using a built-in solution like Apple's [TipKit](https://developer.apple.com/documentation/tipkit/highlightingappfeatureswithtipkit?ref=createwithswift.com) rather than creating a custom popover? I'm concerned about the effort required to build the custom tip view, and TipKit could give us something close:

Yes, I think TipKit is the right way to go if we can customize the colors 👍

**Comment by setch-l** [comment]
@joshuatbrown - Yes we can use the tipkit and it's fine to put it in plain. Also the tickets for the tooltip are intentionally not in this sprint.

**Comment by joshuatbrown** [comment]
@Chardot @setch-l thanks! Regarding the tooltip -- I only started looking at it since the info button is in the sprint and I wanted to avoid releasing a non-functional info button, even if it's only internal.

**Comment by joshuatbrown** [comment]
@Chardot @setch-l I found we can customize the colors in TipKit, but I don't think we can display the tip a second time after the user dismisses it. This obviously doesn't work with our current info button design, so I'd like to propose an alternative -- putting the tip inline in the Discover tab:

![Image](https://github.com/planetary-social/nos/assets/59564/25a46450-3c0b-4907-9dc1-03cb38ee9aaf)

Does this approach seem reasonable? If not, and we want to keep the info button, we may need a new design that uses standard system components.

**Comment by setch-l** [comment]
Hi @joshuatbrown - I don't think we need a permanent message on the page. Let's remove the i icon for now and talk through some options on Monday with Sebastian. I'll book some time on the calendar for the 3 of us to connect.

**Comment by joshuatbrown** [comment]
@setch-l that's fine. To be clear, this isn't a permanent message. As soon as you tap the "x" button, it's gone and won't reappear.

**Comment by Chardot** [comment]
> so I'd like to propose an alternative -- putting the tip inline in the Discover tab:

I think your alternative solution is great, @joshuatbrown! I like it 👍

**Comment by joshuatbrown** [comment]
To summarize the discussion @setch-l, @Chardot and I had this morning: we're not going to implement this right now and instead will remove the info button (#1094). @setch-l I'll let you close or move this ticket where it needs to be.

**Comment by setch-l** [comment]
Not going to work on this for now due to limitations in the iOS code and our need to prioritize the experience in app. In lieu of this we will be adding content to various sections of the website.
