### ISSUE TITLE
[3 Dots Note menu] Update the copy on 3 dots note menu

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1028]
Given that I am a user of nos
When I want to share a note 
Then I should have clear language of what to use inside of Nos and outside of nos. 

AC
Update the menu options to read: 
Copy Nostr note ID 
[share icon] Share note 
Copy note text
View source 
Flag this note
Cancel

**Comment by dcadenas** [comment]
Isn't this the same as #1010 ?

**Comment by joshuatbrown** [comment]
@dcadenas this isn't the same; the copy here is different than what's in that ticket.

**Comment by setch-l** [comment]
@pelumy - Yes. We do not support DMs at the moment so any note can be shared externally.

**Comment by pelumy** [comment]
@setch-l , I see in the ticket description that the share button should have an icon, but with the current implementation, iOS default [confirmation dialog](https://developer.apple.com/documentation/swiftui/view/confirmationdialog(_:ispresented:titlevisibility:presenting:actions:)-9ibgk) does not allow images in the buttons, but only texts. 

To include a share icon, we would need a custom confirmation sheet, which would mean changing the way the code is written for this confirmation sheet. Do we want to invest time in doing this, or it is fine to just use the "Share note" text on the button without the icon?

**Comment by setch-l** [comment]
@pelumy - Please do not include the icon on the button.
