### ISSUE TITLE
Fix Nos Staging test notes

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1044]
The Nos staging builds are no longer displaying any "test notes" aka changelog in TestFlight. These are useful for folks to know what has changed since the last build. I'm guessing something got disconnected during #968 because it's still working for the production Nos app builds.

**Comment by joshuatbrown** [comment]
I'm seeing test notes in TestFlight now for staging, so I'm closing this as completed.
<img width="522" alt="Screenshot 2024-08-02 at 10 12 29 AM" src="https://github.com/user-attachments/assets/4c876569-40c3-466a-a7d2-e9cebe38d91a">
