### ISSUE TITLE
[New Content] Empty Profile Updates

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1068]
Below are stories for the updates we are making to the Profile screen when no notes are available.

## User views a Profile

Given that I am a user of Nos 
When I view a profile tab with no available notes 
Then I should see the following message and a pull to refresh button

We didn’t immediately find notes for this profile. Please try again. 
[Pull to refresh] 

Designs: 

https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A7030&mode=design&t=sChDwE9vXMj1qlTA-1

## Clicking pull to refresh checks for more content 

Given that I am a user of Nos
When I click Pull to refresh on a profile tab 
Then the app should check for additional notes and load any it finds.

**Comment by mplorentz** [comment]
@setch-l @Chardot since we are not prioritizing the animations yet (I think this means no custom pull to refresh stuff) should we change the "Pull to refresh" button to just say "Refresh" for now?

**Comment by setch-l** [comment]
@mplorentz - It depends, can they click on it to refresh or do they still have to pull to have the refresh happen? If they don't need to pull, then changing the copy is great. If they need to pull then I think we need to add the bare minimum animations of content loading. This was one of the things I was hoping to understand from the engineers.

**Comment by mplorentz** [comment]
Yes when they tap the button we can trigger a pull to refresh in the code. It will show the same loading indicator you see when you pull to refresh.

**Comment by martindsq** [comment]
@setch-l The Figma file says "We don't see any notes for this profile, but we'll keep looking!" (which is what we have on production. On the other hand, the description of this tickets says "We didn’t immediately find notes for this profile. Please try again.". Does that mean that I need to update the copy? Bear in mind that we already have translation for the first copy so I suggest updating it only if we feel we have legit reasons to overcome the temporal loss of translations (eventually somebody will translate the new copy again).
