### ISSUE TITLE
[New Content] Display new notes notification on the Profile screen

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1069]
Below are the user stories for notifying the user when there are new notes on the profile screen. See also #1070.

## Users are alerted when new notes are available 

Given that I am a user of Nos 
When there are new notes available 
Then I want to see a notification near the top of my current feed screen that says 

New Notes Available or # new notes 

Designs - Note these will be updated to lavender buttons
https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6021-7030&t=IbI7C8Kr0MhBnMzn-1

## Clicking on the new notes button 

Given that I am a user of nos 
When I click on the new notes button
Then I should see the new notes load and I should be at the top with the latest note.

**Comment by joshuatbrown** [comment]
@setch-l I don't see a design for this in Figma. I see the one on the Feed but not on the Profile. Am I missing it?

**Comment by setch-l** [comment]
@joshuatbrown - I'm not sure what happened when the stories I wrote were translated into iOS tickets. I personally don't think we need to show when new content is available for the profile screen as long as something has loaded. We already have the tap to refresh implemented. Perhaps this came out of the issue we were having where only 5 posts were loading, but we seem to have fixed that issue. 

It's more important to have the new notes available on the Feed. I would skip this for now.

**Comment by joshuatbrown** [comment]
@setch-l that sounds good -- I've stopped working on this. I'll let you move this ticket where it should go and close it if you like.

**Comment by setch-l** [comment]
We're not going to add this now.
