### ISSUE TITLE
[Account Moderation Hot Fixes] Clicking flag this user opens sheet menu

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1082]
Given that I am a user of Nos
When I click Flag this user
Then the sheet menu opens and the user sees the following:

Create a flag for this user that other users in the network can see. 
Spam
Harrassment
NSFW
Illegal 
Other

Designs:
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6068%3A4704&mode=design&t=xo3cClGQ5sl95lOz-1

**Comment by joshuatbrown** [comment]
Note for development: see https://github.com/planetary-social/nos/pull/1063#discussion_r1583283108, which points out that we should be able to use the same categories as the author ones.
