### ISSUE TITLE
[Account Moderation Hot Fixes] Selecting a user flag opens a sheet to post publicly or send to nos

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1083]
Given that I am a user of Nos
When I select a flag to report an account
Then a third sheet should open with the following: 

[reported category] Send to Nos or Flag Publicly
Flag Publicly
Send to Nos
Cancel 

Designs: https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6068%3A4726&mode=design&t=xo3cClGQ5sl95lOz-1

**Comment by joshuatbrown** [comment]
@dcadenas I see a comment you wrote in the code that says this:

```
For the moment, users skip the private vs public report menu and
directly go to the public report until we implement user reports
for reportinator
```

Is this still the case? If so, we'll have to wait to implement this ticket until reportinator is ready.

**Comment by dcadenas** [comment]
> @dcadenas I see a comment you wrote in the code that says this:
> 
> ```
> For the moment, users skip the private vs public report menu and
> directly go to the public report until we implement user reports
> for reportinator
> ```
> 
> Is this still the case? If so, we'll have to wait to implement this ticket until reportinator is ready.

that's right, I'm starting to implement user reporting
