### ISSUE TITLE
[Discover tab] Update tab with categories & Participants R1

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1092]
Please note: Do not pick up this work until April 30th. 

AC -

In addition to the existing folks on the Discover tab for the original work, add the npubs in the categories listed on the sheet, as well as the "New" category: 
https://docs.google.com/spreadsheets/d/1ZS0NsMNyy5BOyjLA9yMEJC1HI7dVEkLwT7SpccPOYGw/edit#gid=0

**Comment by joshuatbrown** [comment]
Moving this back to In Progress as I add the two new accounts from the sheet.
