### ISSUE TITLE
[Discover Tab] Align nav center on an ipad / mac

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1107]
Given that I am a user of Nos
When i view the Discover tab
The nav bar should be aligned left to the content below instead of the "white space" to the left. 

![Image](https://github.com/planetary-social/nos/assets/6765558/772776ce-f972-4677-87f8-6529ebe46765)

**Comment by joshuatbrown** [comment]
Seems like we'd want this centered rather than left-aligned to the content below; otherwise it'll just be hanging off to the right and there'll be a lot more space on the left than on the right.

**Comment by setch-l** [comment]
@joshuatbrown - Any of the above works. As long as it is not left aligned over the "white" space.
