### ISSUE TITLE
[BUG] App crashes after logging out

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1113]
Steps to reproduce:
1. Open the Nos app
2. Navigate around 
3. Go to Settings 
4. Click logout 
5. Do something else on your phone
Issue: App crashes - note it is not right away. 

THis is possibly a sentry report for a crash: https://planetary-app.slack.com/archives/CM4EPK324/p1715009558903329

**Additional context**
[Sentry report](https://sentry.nos.social/organizations/verse/issues/1491/?alert_rule_id=3&alert_type=issue&project=2&referrer=slack) - [matching Slack report](https://planetary-app.slack.com/archives/CM4EPK324/p1719931477701729) - [matching Sentry report](https://appstoreconnect.apple.com/apps/6479681443/testflight/crashes/ALXK7yIngGw8ZdX0psDgsfQ?appPlatform=IOS&sort=-timestamp)

**Comment by mplorentz** [comment]
Here's a [direct link](https://sentry.nos.social/organizations/verse/issues/1231/?referrer=slack&alert_rule_id=3&alert_type=issue) to the sentry report. Hopefully we can run the app with the main thread checker on and catch where this is happening.

**Comment by martindsq** [comment]
I left my findings here https://planetary-app.slack.com/archives/C04PLR5QFQQ/p1717700060630829

In short, it's not reproducible. Let's wait until we have more information. I'm sending this ticket back to the backlog.

**Comment by setch-l** [comment]
this is fixed
