### ISSUE TITLE
[Tagger bot] iOS Updates

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1120]
Update the Reportinator npub to the new Tagger npub in the iOS app:

npub12m2t8433p7kmw22t0uzp426xn30lezv3kxcmxvvcrwt2y3hk4ejsvre68j

**Comment by joshuatbrown** [comment]
Merging the iOS PR for this; it won't work properly until @dcadenas has the new Tagger bot ready: https://github.com/planetary-social/cleanstr/issues/48
