### ISSUE TITLE
Audit code for possible bugs in sheets

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1133]
We recently fixed [a bug](https://github.com/planetary-social/nos/issues/1097) that was caused by using `sheet(unwrapping:)` with a `@State` variable. This is all explained in detail in [the bug report I created](https://github.com/pointfreeco/swiftui-navigation/discussions/151) in `swiftui-navigation`. As you can see there, it's not a bug in `swiftui-navigation` but rather in SwiftUI, and it was converted from a bug report to a discussion.

Let's audit our code for other uses of `sheet(unwrapping:)` and determine whether they're also causing bugs. We can solve them either by using `sheet(isPresented:)` as we did [in this PR](https://github.com/planetary-social/nos/pull/1123), or we can use one of the approaches described in the `swiftui-navigation` [discussion (formerly a bug report)](https://github.com/pointfreeco/swiftui-navigation/discussions/151).

**Comment by mplorentz** [comment]
@joshuatbrown I did a quick search and I don't see any other use of the `unwrapping:` API. Maybe this can be closed? I think if someone tries to use it again it they should catch that it doesn't work in testing. We could maybe mark the functions as deprecated so they don't get used again but I'm not sure if we can do that for external code or if it's even worth doing.

**Comment by joshuatbrown** [comment]
@mplorentz well that was a lot quicker than I expected. You're absolutely right; I'm not finding any other uses, either, so we can probably just close this.
