### ISSUE TITLE
[Bug] Deletes are not appearing on mac

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1143]
Steps to reproduce: 
1. Open Nos on a mac 
2. Create a note 
3. Wait 5 - 15 mins
4. Come back to the app and delete it
5. Refresh the post / your feed / your profile (it doesn't work immediately or 15 min later) 
Issue: The post is still present - although if you check on a phone on Nos it will disappear. 
Expected: When a user deletes a post on a mac, it will automatically delete from the device they are on - even if it takes longer to propogate across the Nostr network. 

This slack post has some log files that might be useful: 
https://planetary-app.slack.com/archives/CM4EPK324/p1715866278085729

**Comment by joshuatbrown** [comment]
I can reproduce this on any device.
