### ISSUE TITLE
[Bug] Cannot upload 8.8MB video

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1149]
**Describe the bug**
We can't upload this video because nostr.build returns the error "File size exceeds the limit of 11.00 MB" but the video is only 8 MB. 

**To Reproduce**
1. Add this video to your device's photo library: https://github.com/planetary-social/nos/assets/1165004/dae596e8-3974-4ce9-9305-97356d87c224
2. Open the note composer in Nos
3. Tap the image icon to upload a video
4. Tap "Select from Library"
5. Choose the video from step 1

**Expected behavior**
The video is uploaded and a link to it is inserted in the note composer

**Screenshots or Video**
![Screenshot 2024-05-16 at 2 17 08 PM (1)](https://github.com/planetary-social/nos/assets/1165004/f86304f2-67a3-4c58-a80d-b3828907ce01)

**Comment by joshuatbrown** [comment]
Here's what I got in the HTTP response from the nostr.build API:

```
{
  "status": "error",
  "message": "File size exceeds the limit of 7.00 MB",
  "data": {}
}
```

So, apparently 7MB is the file size limit? I did some further testing and confirmed that it seems like 7 is indeed the limit.

**Comment by joshuatbrown** [comment]
Also confirmed on [the Nostr.build about page](https://nostr.build/about/) under "Free services":

> Media (images, audio and video) uploads up to (7MB) hosted on Cloudflare

**Comment by joshuatbrown** [comment]
I'm going to suggest we close this, implement #1208, and see what the limit is there. Maybe it'll be higher, but at the very least, I'll make sure we have error handling in place to accurately inform the user of what's happening.

**Comment by mplorentz** [comment]
Can we leave this open and just indicate that it's blocked on #1208? That way we can make sure we test this specific flow again at some point, in UAT and everything.

**Comment by joshuatbrown** [comment]
Tested with the NIP-96 API, and I'm still seeing a 7 MB limit.
