### ISSUE TITLE
[BUG] nos.social NIP05's strike-through

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1161]
Not entirely sure these are the steps to reproduce, but I think it involves logging in and out...

Steps to reproduce: 
1. Log into nos.social with NIP05 account
2. Logout 
3. Either generate a new key or log in with another account
4. Logout
5. Log in with the first account
Issue: The original NIP05 address has a strike through. 

Note this has happened to my account, but also one of the Journalists. Daniel is seeing on his side that the Kind 0 is not being set properly. 

More info from daniel can be found in slack here: https://planetary-app.slack.com/archives/CM4EPK324/p1716299650187269?thread_ts=1716299347.451059&cid=CM4EPK324

![Image](https://github.com/planetary-social/nos/assets/6765558/9b6eb02d-de0d-420b-99cc-0f9e86df82dd)

**Comment by martindsq** [comment]
Just for the record, in that slack conversation, Daniel said that Kind 0 is being set properly. After expressing doubts about it, he checked some relays and the kind 0 was fine. So I'm looking for something else.
