### ISSUE TITLE
[Media Display] Display images with new image viewer

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1164]
We are improving the way images are displayed alone or in a media gallery. In particular there is a new set of interactions when tapping the image. Instead of opening it in a web view there is a new fullscreen view that will appear that allows zooming and panning.

Images displayed should match these [Figma designs](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6290%3A18443&t=d5r4Y8GVjDK1s4oZ-1) and fulfill the following [stories (detail)](https://docs.google.com/document/d/1lVLcwrYFbYS96O3yogrtiYnRU3ICUhh0UIMO6HD1e1U/edit):
- Tapping a single image once, opens to full screen 
- Double tapping a full screen image will zoom to fit entire screen
- Users can pan images in zoom screen view 
- Users can click x or swipe down to close image

We are leaving aspect ratio changes for #1171.

**Comment by setch-l** [comment]
This works except for swiping down to close the image, but I'm ok without that functionality. Nice work!

**Comment by joshuatbrown** [comment]
@setch-l I'm surprised swiping down doesn't work for you. Well, unless you were zoomed in. If you're zoomed out, swipe down to dismiss should work. If you're zoomed in, swiping any direction just moves the image around.
