### ISSUE TITLE
[Media Display] Fetch OpenGraph metadata for links

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1165]
To determine the media type of a link we can look at the file extension but if a URL doesn't have one we should use the Open Graph Protocol to get an image or video we can use as a link preview. This ticket should add code to download this the Open Graph data and use it to determine whether to render a link preview as an image, video, or placeholder (final placeholder will be added in #1170). Additionally, if it's an image or video, add code to determine whether it should be shown in portrait or landscape mode based on the Open Graph data.

**Comment by joshuatbrown** [comment]
@setch-l No changes visible to the user on this one, so nothing to test on your end. This will show up in #1425 and others.
