### ISSUE TITLE
[Media Display] Replace gifs with new gif viewer

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1168]
We are improving the way gifs are displayed, alone or in a media gallery, according to these [Figma designs](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6290-21425&t=d5r4Y8GVjDK1s4oZ-0). We have separated aspect ratio changes into #1171. For now all gifs will be displayed 4:3 aspect fill. 

Gifs displayed should fulfill the following stories [(detail)](https://docs.google.com/document/d/1lVLcwrYFbYS96O3yogrtiYnRU3ICUhh0UIMO6HD1e1U/edit):
- Gif Viewing in Nos

**Comment by joshuatbrown** [comment]
@setch-l Suggested testing steps:

1. Navigate to Settings
2. Toggle Enable new media display to "On"
3. Find or post a GIF (here's a note with one: `note1nvf6wm257sku94zt9dqaw439a67dg6qq8wwjh9xg2pny07rpvk8qp8xkcq`)
4. Tap anywhere on the GIF to play the animation
5. Tap a GIF that's animating to view the GIF full screen
6. Double-tap to zoom in the full-screen viewer
7. Double-tap to zoom out
8. Tap the "X" button or swipe down to close the image viewer

**Comment by setch-l** [comment]
@joshuatbrown - When I follow the steps above on a mac - the gif auto-plays. On a phone I need to click it. I don't think this is a big issue so I'm going to continue the ticket forward.
