### ISSUE TITLE
[Media Display] Use NIP-92 media metadata

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1172]
https://github.com/nostr-protocol/nips/blob/master/92.md

**Comment by joshuatbrown** [comment]
@setch-l steps for testing:

1. Navigate to Settings
2. Enable new media display
3. Navigate to Feed or Profile
4. Find some media with an `imeta` tag (note1cj6xmz48ausu04mckl4ral8qec4j4sz7akr4uarewwchsydywraq8jwkt8). If you upload an image or video with Damus, it'll contain the `imeta` tag.
5. See if it's displayed correctly based on the tag
