### ISSUE TITLE
[Media Display] Build new gallery view

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1177]
We are updating the look of our media gallery view [Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6290%3A22017&t=d5r4Y8GVjDK1s4oZ-1). This ticket includes the new styling of the gallery: the solid chrome under the media and the custom page dot indicator, and the change in aspect ratio from square to 4:3 (vertical media will be handled in #1171). 

This ticket doesn't include the new styling for link metadata or the new viewers for the different media types, so the media displayed within the gallery will be the old Apple link previews until other tickets like #1164, #1166, and #1168.

**Comment by joshuatbrown** [comment]
@setch-l We have this feature behind a feature flag that defaults to off. To turn it on so you can test, do the following:

1. Navigate to Settings in Nos Staging
2. Find "Enable new media display"
3. Toggle it on
4. Go back to the view and observe the custom page dot indicator, and the change in aspect ratio from square to 4:3

The new custom page dot indicator has an orange dot marking the selected page, so if you see the orange dot, you have "Enable new media display" turned on. If you see the white dot marking the page, the feature is turned off.

**Comment by setch-l** [comment]
This looks good.
