### ISSUE TITLE
[Copy Link] Change copy to copied when user clicks copy

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1181]
Given that I am a user of Nos viewing the Settings screen
When I click copy on the private key 
Then I should get feedback that the key has been copied
AND the button changes to Copied for 10 seconds and then changes back to Copy

Designs: 

https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=6396%3A603&t=5qwDF2FcxzEZMXlO-1

**Comment by martindsq** [comment]
@setch-l I think 10 seconds seems too much to me, I seldom stay that much time staring a screen. What about changing that requirement to 3 seconds?

**Comment by martindsq** [comment]
I put a video at https://github.com/planetary-social/nos/pull/1203 showing how 10 seconds looks like
