### ISSUE TITLE
[BUG] Relays count on Feed is inaccurate

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1185]
Steps to reproduce 
1. Install the nos app
2. Log in with a key
3. Navigate to the feed
Issue: The relay count is inaccurate. 
Expected: No one knows what this number is - lets remove it from the screen to reduce the number of things that need to load for now. 

![Image](https://github.com/planetary-social/nos/assets/6765558/adc1e000-8278-43bc-9593-37fa30415069)

![Image](https://github.com/planetary-social/nos/assets/6765558/ffc7f6ca-4d3c-4f08-89e2-62ee793df43b)

**Comment by mplorentz** [comment]
@setch-l when we remove the button can we put the old stories button back? We used to have a button to open the stories interface that rotated when pressed. It's the same button that shows up when you are in the stories interface to get out of it, but we removed it from the home feed when we added the relay count. It was nice and it shouldn't add much work, we just need to look through the code history and put the old code back.

![Image](https://github.com/planetary-social/nos/assets/1165004/1ca741a2-6707-4fe9-953f-948a741a8c9c)

**Comment by mplorentz** [comment]
I'm not worried about people getting into the stories view. I don't think it's obvious how to get out. The icon we have for it doesn't make any sense unless you see it animate when you transition into the stories view. And you can tap the home tab but I don't think most people know to try that. 

I guess not many people are using this view right now, but we had a better user interface, we made it worse when we added the relay count, so I wanted to go back to the better version. But we've probably spent longer discussing it now than it would take to actually implement it. So I'll drop it.

**Comment by setch-l** [comment]
We are going to do something different to resolve this issue. Closing for now
