### ISSUE TITLE
[Design] Design states for link not loading and error of media not loading

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1186]
Acceptance criteria
Design UI for the following experiences
- When an opengraph preview is not available show the link (user should still have option to click through on link) 
- When media of any kind has trouble loading what does the user see?

**Comment by Chardot** [comment]
I designed a "broken link" icon to display when media –including opengraph previews– does not load:

![Image](https://github.com/user-attachments/assets/81e02b9f-5882-40cc-bab4-362f4a697037)

I went for a subtle embossed effect that gives the appearance of emptyness or "something is missing here".

This is the .SVG icon: 

![Image](https://github.com/user-attachments/assets/57396c6d-d3c1-4b00-be65-5147c59f5894)


Here's [the design in Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7967-1058&t=pOfZIAMsQMkl0QV5-1).
