### ISSUE TITLE
[Bug] Taking a photo / video from the app does nothing

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1211]
While uploading an existing photo / video works, taking a photo or video from the app does nothing. 

Steps to reproduce
1. Open Nos
2. Click on Post
3. Click on photo icon
4. Select take a photo / video
5. Take photo 
6. Upload it
Issue: Nothing happens in the app.

**Comment by joshuatbrown** [comment]
I can reproduce this.
