### ISSUE TITLE
Prevent feed from jumping when new posts come in

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#122]
Nos streams in new notes on the Home, Discover, and Profile screens and shows them right away. If you have scrolled down this can cause the note you were looking at to move, which is really annoying. Let's figure out how to prevent the scroll view from jumping, or maybe stop inserting new notes into the feed immediately, instead hiding showing a "new posts" toast that the user can tap to scroll to the top and refresh, like Planetary.

**Comment by setch-l** [comment]
This is fixed, but we don't show you new posts.
