### ISSUE TITLE
Clean up NIP-96 & NIP-98 photo and video upload code

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1223]
Since nostr.build was [planning](https://github.com/nostrbuild/nostr.build/pull/70) to shut down their unauthenticated API today (June 6), we quickly implemented NIP-96 & NIP-98 in #1208. We'd like to get the code cleaned up and refactored by doing a few things:

- delete the old file upload code (that uses v2 of the nostr.build API)
- if we don't get the API URL before a user tries to upload an image, fetch the API URL from the nip96.json endpoint
- don't get server info when the app is launched to minimize processing and improve performance at app startup
- delete refreshServerInfo() if we're no longer using it

**Comment by rabble** [comment]
So looking at what Damus puts in the note when uploading with nip96/98 we get this:

{
  "content" : "And this is an experiment to see how it compares to Damus doing the same thing. https:\/\/i.nostr.build\/dw0BJ.jpg ",
  "tags" : [
    [
      "e",
      "19a703806c8a07fccccacfffbe0fd5eb13f4b83150a6d89e25d618c4f29530ca",
      "",
      "root"
    ],
    [
      "imeta",
      "url https:\/\/i.nostr.build\/dw0BJ.jpg",
      "blurhash eJJ*VK=x-A-p.SJD-;MwIUo}_NkWDh%LjZ0fE2V?-p-pD*-oM|R.S5",
      "dim 5712x4284"
    ],
    [
      "r",
      "https:\/\/i.nostr.build\/dw0BJ.jpg"
    ]
  ],
  "sig" : "6b59ec2a0d0a2cfec5d8b0f0a6a763e1e995b9cceca02d65a759e411edcb2ae6e08a0c3fa4b7417326c43a232a890b9c400a339c69aa661dff95c932a56baed5",
  "pubkey" : "76c71aae3a491f1d9eec47cba17e229cda4113a0bbb6e6ae1776d7643e29cafa",
  "kind" : 1,
  "id" : "27ec3a97d002572ee16f6fcfcd03b1323cc861391f0acecec5199a835ea90086",
  "created_at" : 1717721237
}

vs what we’re adding:

{
  "content" : "https:\/\/i.nostr.build\/roAlG.jpg\n\nThis is a test of the new nip-96\/nip-98 upload system we’re finally adding to Nos. ",
  "tags" : [

  ],
  "sig" : "0ad6299d69252aaf98c11512b1f3daf47eeee91d72d0761064f4afc7afff24963b709377ef3dc08436fd70f55d0fd8e755310850c26fb561d76c09d51e4d7904",
  "pubkey" : "76c71aae3a491f1d9eec47cba17e229cda4113a0bbb6e6ae1776d7643e29cafa",
  "kind" : 1,
  "id" : "19a703806c8a07fccccacfffbe0fd5eb13f4b83150a6d89e25d618c4f29530ca",
  "created_at" : 1717720840
}

The imeta stuff comes from NIP 92 & nip 94:

https://github.com/nostr-protocol/nips/blob/master/92.md

https://github.com/nostr-protocol/nips/blob/master/94.md

It should be pretty easy add these to the ticket and would go a long ways towards improving our experience with file attaching to posts.

**Comment by setch-l** [comment]
@rabble - I'm curious what the user gets from NIP92 and 94? I see that there is some additional meta data that is included with one of them, but I'm not sure what else. 

The main difference I noticed is that Damus gives a slick image preview with the option to delete the uploaded image whereas we simply provide a text link and the user has no idea if they even uploaded the correct image. It doesn't seem like either of these NIPs will resolve that issue, but perhaps I'm missing something. 
![IMG_8291](https://github.com/planetary-social/nos/assets/6765558/949b4424-9170-4a0e-8877-7a0f8ef5a22d)

**Comment by joshuatbrown** [comment]
@setch-l I can confirm that we _could_ display a preview of the image with the data we have now (from NIP-96). Just need design to do that. But maybe there's something else NIP-92 and 94 could do. @rabble?

**Comment by setch-l** [comment]
Good to know. I'm going to wait for a real ux designer for that design though.
