### ISSUE TITLE
[bug] support for this nevent format is broken in Nos

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1231]
Steps to reproduce
1. Open this note in Nos: note1qq7am022xm40yrj9k4agcfqwre4lflsq6mytky0suxunrk7ldf5sjwth8x
Issue the formatting of the event is not supported and renders as the event ID see screenshot below
EXPECTED: This is either a link to a note or renders as a quoted note (once we support those) 

![Image](https://github.com/planetary-social/nos/assets/6765558/65a68e42-221e-440f-a9cc-24f8d5a44630)

**Comment by joshuatbrown** [comment]
Other notes to test that contain nevents that should show the "🔗 Link to note":

- note1ypppzcue3svj2p0l80vp4lf52j3xmykn8yzjdv3gnq2sm4ljp5qqrqp9hd
- note16fddcyxfldwre2zywr96fnkmk7n3rtf4ehntdwy8ltyqgfntwfnq0dm347
