### ISSUE TITLE
[bug] Punctuation after a url breaks the url formatting

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1233]
Steps to reproduce
1. Write a text note and use nos.social or another url with punctuation at the end like: nos.social. 
Issue: We do not strip out the punctuation and as a result, the preview link is broken and there's a protocol error in the browser (for our site at least). 
Expected: If a user enters a period, comma, colon or semi-colon after a url then we should strip it out when generating the link and the link preview. 

You can test this with this note: note1l4gf7095vkvylx4sn5u5t635y94jcwqlq4z33awc678lcm8zrktsyjjf3p

![Image](https://github.com/planetary-social/nos/assets/6765558/cae586b2-895a-4e6c-b2f0-662c9f8134ed)

**Comment by joshuatbrown** [comment]
@setch-l Reopening and putting into QA since this will be in the 0.1.25 build.
