### ISSUE TITLE
[Analytics] Track publishing of replies in Posthog

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1250]
It looks like this metric was disabled either when the migration happened or during another update. 

AC - 
Using Posthog I should be able to see: 
- number of unique users replying to posts
- Funnel of replies (are they coming from notifications tab or within a thread) 
- Total number of replies

**Comment by mplorentz** [comment]
This was a very simple fix that I went ahead and did during a meeting or something when we were talking about it, so I'm moving this to Code Review.
