### ISSUE TITLE
[3 Dots Note Menu] Clicking share note

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1272]
Given that I am a user of Nos
When I click Share Note on the 3 dots menu 
Then the share sheet should open and I can choose where I want to share an njump me link to a note.

**Comment by mplorentz** [comment]
@pelumy we did something very similar to this in our old app Planetary. You can find that code [here](https://github.com/planetary-social/planetary-ios/blob/45e5f08bdba6c5b620131086612c8cba03a463e9/Source/UI/Message/MessageOptionsButton.swift#L76) if you want to read or copy any of it. We have a similar view in Nos named `NoteOptionsButton.swift` which is probably where you will want to start.

**Comment by pelumy** [comment]
Thanks for these tips @mplorentz 🙏🏾
