### ISSUE TITLE
changing private key in settings does not update HomeFeed

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#128]
If you put a new private key into the settings and save it the stories view at the top of the home feed does not update based on your new follower list.

Steps to reproduce:
1. Create a test account and follow one user who has posted within the past 24 hours. Save the private key (nsec) of this user.
2. Log out and create another test account and follow a different user who has posted within the last 24 hours. Save the private key (nsec) of this user.
3. Open the Settings screen from the side menu.
4. Paste in the private key of the user from step 1 and tap Save
5. Navigate back to the home tab
Expected: The person you followed in step 1 is shown
Actual: The person you followed in step 2 is shown in the stories carousel at the top

<img src="https://github.com/planetary-social/nos/assets/1165004/739a1e2f-f4f9-4266-8f6d-31b53071bbcc" width="300" />

**Comment by setch-l** [comment]
@mplorentz - Please test this and verify it is done.

**Comment by mplorentz** [comment]
Looks like the HomeFeed still has a bug. The scrollable feed gets updated but the stories carousel does not. I'll add steps to reproduce and update the description to be more specific, and send this to the backlog.

**Comment by setch-l** [comment]
This is fixed on build 0.1.5 (189)
