### ISSUE TITLE
[Discover Tab Update] Add Cohort 4 to the Discover tab

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1283]
AC
- Add Cohort 4 to the Discover tab 
- Move the existing folks down on All, and other topical categories
- Remove existing group from New

**Comment by rabble** [comment]
Add Edward Snowden ( npub1sn0wdenkukak0d9dfczzeacvhkrgz92ak56egt7vdgzn8pv2wfqqhrjdv9 )  and myself  ( npub1wmr34t36fy03m8hvgl96zl3znndyzyaqhwmwdtshwmtkg03fetaqhjg240 ) under both tech and activism and then add protest.net under activism (npub1z3thwmwasmp787zvk2aaq5qdjtjdkl637p52nph4flv668973c8qaz2du7)
