### ISSUE TITLE
Set up side menu + tab bar

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#13]
Right now all our main views (Home feed, relays, settings) are presented in a single `NavigationStack`. Let's move the Home Feed and Relays into a standard tab bar component, and put the Settings in a side menu that opens from a little profile avatar in the top left of the HomeView and RelayView, just like Planetary. Don't worry about icons or styling for now.

The Planetary side menu and tab bar are built using UIKit, but we'll want to do these in SwiftUI in Nos so there won't be much code that we can copy. But there is a standard SwiftUI tab bar that we can use, and there is probably a lot of example code for a side/hamburger style menu out on the internet we could use. (Planetary's side menu doesn't open if you swipe from the left side of the screen, it would be great if we could support this in Nos, but let's not spend too much time on it).

**Comment by jcswift23** [comment]
https://github.com/planetary-social/nos/pull/36
