### ISSUE TITLE
Crash on logout

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1301]
**Describe the bug**
Sometimes when logging out the app crashes

**Additional context**
[Sentry report](https://sentry.nos.social/organizations/verse/issues/1491/?alert_rule_id=3&alert_type=issue&project=2&referrer=slack) - [matching Slack report](https://planetary-app.slack.com/archives/CM4EPK324/p1719931477701729) - [matching Sentry report](https://appstoreconnect.apple.com/apps/6479681443/testflight/crashes/ALXK7yIngGw8ZdX0psDgsfQ?appPlatform=IOS&sort=-timestamp)

**Comment by setch-l** [comment]
@mplorentz - this is a dupe of #1113 - I'm going to leave it open bc both have information.

**Comment by mplorentz** [comment]
oh #1113 looks better. I'll just copy the links from here to that one and close this one.
