### ISSUE TITLE
Nos downloads too many events at launch

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1309]
When Nos launches I often see like 5000 events get added to the parse queue. This is way more events than we need - lets diagnose what subscriptions are requesting so many and find some ways to cut them down. This will improve the app performance on launch.

We have had reports from users that profile photos don't load - my theory is that they get stuck in the parse queue and are caused by this problem.

**Comment by setch-l** [comment]
I tested this by doing the following: 
1. Logout of staging on build 371
2. Delete the app
3. Install a new version of the app
4. Generate a new key
5. Let the Discover tab sit there - I ended up doing it for 17 min bc I was messing with other stuff. 
Issue: came back and only 4 of the profiles on the Discover tab were loaded 
I think I clicked refresh and the rest populated.

**Comment by mplorentz** [comment]
🤔 if it sat there for 17 minutes that definitely should be enough time to download all the events it asked for, so think there is another issue going on here. We should probably file a separate ticket for that.

**Comment by joshuatbrown** [comment]
@setch-l I removed the Stories UI so when you're testing, look at the Feed and make sure everything is good there. You'll see that there's no Stories UI but otherwise should look and feel about the same. Maybe it'll feel slightly better or even a lot better depending on how much processing Stories was taking for you.

**Comment by mplorentz** [comment]
Removing the stories view helped a lot but right now I'm able to reproduce a dump of 2000 events into the parse queue on one of my test accounts. I'm going to dive into whats causing it before we close this ticket.

**Comment by mplorentz** [comment]
I filed https://github.com/planetary-social/nos/issues/1365 to track the above, and I'm moving this ticket to UAT.
