### ISSUE TITLE
NIP-05 sheet is shown after reinstalling Nos

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1310]
**Describe the bug**
The NIP-05 sheet is popping up after deleting the app - even if I have a registered NIP-05

**To Reproduce**
1. Log in with an account that has a NIP-05 configured
2. Delete Nos
3. Reinstall Nos
4. Open Nos

**Expected behavior**
The NIP-05 sheet is not presented.

**Screenshots or Video**
The NIP-05 sheet is presented.
<img src="https://github.com/user-attachments/assets/ee91517b-0074-4983-a88e-5f2d0fd79541" width="300" />

**Technical info (please complete the following information):**
 - OS: iOS 17.5
 - App Version: 0.1.21 (361)
 - Environment: Staging

**Additional context**
My guess is that we aren't waiting for the profile data to be downloaded before deciding whether to show the NIP-05 sheet.

**Comment by joshuatbrown** [comment]
@setch-l Reopening and putting into QA since this will be in the 0.1.25 build.
