### ISSUE TITLE
[N things] Replace nprofile with NIP05 if user has one

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1312]
Given that I am a user of Nos
When I am viewing an nprofile link in the app that is associated with a user who has a NIP05
Then I should see the NIP05 as a link instead of a long string.

**Comment by joshuatbrown** [comment]
For example, [this note](https://njump.me/note1sr90mze0x6elk0m3kxg88dh45fpxfzppp7s6hmvrl8trau46g0qqy77hgh) should say "Hey @Josh Brown!":

Here's what it currently looks like in the app:
<img width="627" alt="Screenshot 2024-08-08 at 9 23 35 AM" src="https://github.com/user-attachments/assets/7c8eb39c-1529-40a3-90d5-8fb501dbdd0d">

We do render the NIP05 username for npubs, as you can see in [this note](https://njump.me/note1cserrckywpdxx2e8n83uxyc2sdku6pxjs2dnc8fav078eewfgmtst9q0mx):

<img width="627" alt="Screenshot 2024-08-08 at 9 25 12 AM" src="https://github.com/user-attachments/assets/63688da9-3a54-4432-8199-816badaeaef6">

**Comment by setch-l** [comment]
This work was done as part of something else.

**Comment by joshuatbrown** [comment]
@setch-l We still have some work to do on this. We've covered `nostr:nprofile` references but not `nprofile` references without the `nostr:` prefix.
