### ISSUE TITLE
[Design] Design UX experience for image previews

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1340]
- [x] Read through the product brief https://www.notion.so/nossocial/Image-Note-Preview-2bc95913851c4459a873ec57757bda50
- [x] Document the existing experience in Nos
- [x] Review the competition 
- [x] Create wireframes 
- [x] share w/ Linda
- [x] Create mocks including all edge cases / use cases 
- [x] share with Linda 
- [x] Revisions if necessary 
- [x] Prep for Design Review 
- [x] Document & implement action items from Design Review 
- [x] Prepare files for developers

**Comment by Chardot** [comment]
First, I documented [the current experience](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-2973&t=gtSV1sR7g5G3ExxL-1) for adding a photo to a note in Nos:

![Image](https://github.com/user-attachments/assets/13075086-83e0-405f-b53e-e1237172c0df)

Then I documented the same experience in [Primal](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-2009&t=gtSV1sR7g5G3ExxL-1) and [Damus](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-3395&t=gtSV1sR7g5G3ExxL-1):

![Image](https://github.com/user-attachments/assets/389a4330-90e5-43be-b14a-646e8f725e3d)

Then I made [wireframes for two different user flows](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-3395&t=gtSV1sR7g5G3ExxL-1):

1. In editor image preview
2. Dedicated preview UI

After reviewing both options, Linda gave me approval for applying the [UI styles to the Dedicated preview UI](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7413-6822&t=gtSV1sR7g5G3ExxL-1), keeping the editor header actions (cancel, select relay, post):

![Image](https://github.com/user-attachments/assets/386b1ea1-0cfb-48c5-8a7f-e40e553af524)

**Comment by Chardot** [comment]
After reviewing the [research](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-2973&t=v7fXqtePw7vJBCVq-1), [wireframes](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7322-1864&t=v7fXqtePw7vJBCVq-1) and [initial designs](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7440-1069&t=v7fXqtePw7vJBCVq-1), [I designed a new iteration](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7554-2407) that captures the feedback given on the previous designs.

It's implementation will be divided into 3 phases:

[Phase 1: Image URL in editor](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7554-3294&t=v7fXqtePw7vJBCVq-1)

In this first phase of implementation, the editor will continue showing the URL of the image uploaded, while allowing the user to preview the note as it will be published.

![Image](https://github.com/user-attachments/assets/439f667e-9e75-4665-bb8e-798ab0f9d82b)


[Phase 2: Image preview in editor
](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7568-12019&t=v7fXqtePw7vJBCVq-1)

For the second iteration, the editor will display a preview thumbnail for each image or video uploaded. Thumbnails will be displayed as block elements in the editor scroller, so the user will have to scroll vertically to check all the images that are attached to the note.

![Image](https://github.com/user-attachments/assets/31f3086d-b27f-4ce4-932f-0888df8026f0)

[Phase 3: Inline scrollable multiple image previews](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7568-13622&t=v7fXqtePw7vJBCVq-1)

In the final implementation, multiple image thumbnails will be displayed as inline elements in a horizontally scrollable row.

![Image](https://github.com/user-attachments/assets/59aaafba-bc78-4370-b2ef-e55a8edddade)
