### ISSUE TITLE
[Analytics] Track # of notes & accounts sent to Nos for Moderation

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1351]
Overview 
While we have a slack channel for managing these requests, it would be good to see have metrics on how many notes are being sent to Nos for Moderation 

AC 
- Track the number of notes being sent to Nos for Moderation 
- Track the number of accounts being sent to Nos for Moderation

**Comment by martindsq** [comment]
@setch-l I think we are already tracking this, we send a Reported event when the user sends a report request to our relay. To illustrate this, I created an insight in PostHog https://us.posthog.com/project/56924/insights/UFtVzLWP you can see the total number of reports broke by report type (note or profile). Please, let me know if this is enough for you.
