### ISSUE TITLE
Remove like and repost count from home and profile feeds

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1358]
![Image](https://github.com/user-attachments/assets/f85dad81-9ba1-407a-926f-9e78f410951a)

These numbers are wrong until you tap on the note and open the thread view, so let's not show them until then because it's confusing users.

**Comment by setch-l** [comment]
Hi @martindsq - This is not a well written ticket. The intention was to remove the counts from the main feed until the user has clicked into a thread and then show them back out on the main feed. 

It's this part of the ticket: "so let's not show them until then" 

Can you allow the counts to show in the main feed after a user clicks into a thread?

**Comment by mplorentz** [comment]
@setch-l oh, we definitely miscommunicated here, I thought the above was what we agreed on.

I'm confused by the requirement you are suggesting, because that's basically how the app currently works. We don't show any like or repost counts until you tap into the note. But after tapping into the note and tapping the back button the correct counts are displayed. The exception is if you have liked or reposted the note we will show a count of "1" along with the orange version of the heart/repost button. But that is a rare case because most people are mostly browsing notes they haven't seen before (I assume).

I thought the main problem we are seeing with the current system is that people scroll the home feed and think "this note has no likes or reposts" because some notes in the main feed show counts and some don't. If we continue showing counts on some notes in the feed and not others I think people will continue to think notes with no numbers have no likes. By removing all counts from the feed then it becomes clear that the app just isn't displaying counts in the feed at all.

What do we gain by showing the counts on the feed _after_ you have viewed the note in the thread view? The user has already seen the counts at that point and they are now almost certainly moving on to view other notes at that point.
