### ISSUE TITLE
[Design] Zaps phase 1 - Zap Notifications

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1368]
For Nos Creators and Journalists we want to let them know they've received zaps without them having to leave the app. 

Deliverables: 
- Review & Document the competition's zap notifications: Primal, OpenVibe, Damus 
- Create wireframe option(s) that show who sent the zap, for what, and the amount, as well as the time, bonus if you can capture the emoji / message 
- Meet with Product to review both 
- Design UI based on wireframes 
- Review with engineers
- Final designs

**Comment by Chardot** [comment]
[I wireframed a simple user flow](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7473-33096&t=qosPeXADtBV3uInA-1) for getting a notification banner while browsing the feed, tapping on that banner, seeing the zap in the Notifications screen, and tapping on the zap notification to open the note that received the zap:

![Image](https://github.com/user-attachments/assets/e5d7e927-e6d7-4f3a-87a9-8b4db1da034a)

I reviewed those wireframes with Linda and collected feedback to improve the user experience, adding a [Say thanks] button that opens the note editor with a preloaded message saying thanks for the zap. [I applied visual styles to the design at this point](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7444-30919&t=qosPeXADtBV3uInA-1):

![Image](https://github.com/user-attachments/assets/2a76ec2d-e124-4fcb-b076-c5d8bfab1098)

@setch-l Let me know if this iteration captures what we discussed in our checkin yesterday. I'm moving this to UAT.

[Here's the link to all these designs on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7444-30917).

**Comment by setch-l** [comment]
Hi @Chardot - One of the use cases is missing - saying thanks for a zap to a note - which would be a reply to the note unless you think it should be a direct 1 off message.

**Comment by Chardot** [comment]
> Hi @Chardot - One of the use cases is missing - saying thanks for a zap to a note - which would be a reply to the note unless you think it should be a direct 1 off message. 

You're right, I missed that case. Thanks for catching that. I'll add that case right now. It will be ready in a few minutes.

**Comment by Chardot** [comment]
> Hi [@Chardot](https://github.com/Chardot) - One of the use cases is missing - saying thanks for a zap to a note - which would be a reply to the note unless you think it should be a direct 1 off message.

[I added a case where the user taps on the [Say thanks] button in a zapped note notification](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7478-33477&t=inVddf9GMK8uqqBv-1), which opens the reply editor containing the original zapped note at the top, and a preloaded "@user thanks for your zap!" message:

![Image](https://github.com/user-attachments/assets/5bdd4e54-2a75-449f-8ef0-93f3ce2b271f)

This is how [the complete user flow ](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7444-30919&t=inVddf9GMK8uqqBv-1)looks like:

![Image](https://github.com/user-attachments/assets/590371af-e3b0-4db4-af4c-b03f1e9470f2)

I also replied to questions [on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7444-30917).
