### ISSUE TITLE
Display a notification when your profile is zapped

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1371]
When a user's profile is zapped we want to notify the user. For this first ticket let's only show a notification when the user's profile is tagged in a zap receipt, and we'll handle zapped notes in a separate ticket. We'll need the `PushNotificationService` to listen for zap receipt events, creating NosNotification objects when new zap events are detected in Core Data. These will be displayed both as a local notification (in `PushNotificationService.showNotificationIfNecessary(for:)`) and should show up in the notifications tab (`NotificationsView`).

For details see the [user stories](https://docs.google.com/document/d/1Us_54hgMFVZugio2wuGrFP_UrWkqxi3QNz1Hg79rWNk/edit) and [Figma designs](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7478-33530&t=0GEpFao0Riep9yDl-0).

**Comment by joshuatbrown** [comment]
@bryanmontz I'm not sure if we explained the process to you, but I'm moving this ticket to UAT since the PR was merged.
