### ISSUE TITLE
Replace all Color(hex:) references with Color constants

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1375]
SwiftGen generates color constants based on our colors defined in `Colors.xcassets`. We should only use the color constants and never use `Color(hex:)`. Let's replace all instances with color constants, and if there are no constants, create new colors in `Colors.xcassets`. Let's also replace any uses of `Color(red:green:blue:opacity:)` and `Color(white:opacity:)`.

See #733 for more context (this is essentially a dupe of that).

**Comment by joshuatbrown** [comment]
@lingoslinger thanks! I've assigned it to you.

**Comment by lingoslinger** [comment]
Some questions as I begin work on this issue:

- is there an established naming convention for the Colors asset catalog, or should I use my best judgement?
- when I encounter a hex color that is already in the Colors asset catalog, should I re-use that color despite that color having a specific name, or duplicate the color with a more use-specific name?
- do you want other non-asset-catalog instances of Color replaced (Color(red, green, blue. opacity), Color(white, opacity), etc)?

**Comment by joshuatbrown** [comment]
@lingoslinger the goal is to use semantic naming for the colors -- see the ones that are already there for examples, like `action-primary-background`. And yeah, I think replacing the other Color inits is a good idea, too.

**Comment by joshuatbrown** [comment]
@setch-l for UAT, we'll just want to make sure the colors are still the same. Let us know if any color in the app seems off.
