### ISSUE TITLE
Replace relay.snort.social in our default relay list

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1377]
Updated: Aug 27, 2024
Let's replace the snort social relay with our own version of Fiatjaf's countries relay. 

This relay is no longer publicly writeable, so let's replace it with one that is.

Official note about relay.snort.social moving to subscription only from Kieran: https://njump.me/nevent1qqsfuk42j625l0er3tsm9wvgnyj3g7dv5psv0h94gfh28sz7pjvprqczyp3lucccm3v9s087z6qslpkap8schltk427zfgqgrn3g2menq5zw6mg04rg

**Comment by joshuatbrown** [comment]
relay.nos.social is in the list and [now publicly writeable](https://github.com/planetary-social/infrastructure/issues/131); is that sufficient or do we want to add another?

**Comment by mplorentz** [comment]
I looked into using fiatjaf's [countries](https://git.fiatjaf.com/countries) relay (also running at countries.fiatjaf.com) and it looks really cool. But we'd need to do some dev work to spin our own instance up if we wanted to have a relay like this in our default list.

**Comment by setch-l** [comment]
dupe - this work is done
