### ISSUE TITLE
[Bug] Search sometimes fails to show results

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1393]
## Describe the bug
Searching for a NIP-05 name or any text often fails.

## To Reproduce
1. Delete the app and reinstall
2. Tap Discover
3. Type a search term into the box, like "matt"
4. Observe that no results appear (or very few)

## Expected behavior
The results should show lots and lots of Matts; there are lots of them and nostr.band has them.

## Screenshots or Video
https://github.com/user-attachments/assets/454196b9-815a-4c0c-8213-15355972877a

## Technical info
 - OS: macOS, iOS
 - App Version: `main` branch, Staging 0.1.24 (399), 398, 397
 - Environment: Dev

## Additional context
[Rabble's report on Slack](https://planetary-app.slack.com/archives/CM4EPK324/p1723161285951389)

Run this to see lots and lots of results (probably 50):

```
echo '{"kinds":[0],"search":"matt","limit":50}' | nak req wss://relay.nostr.band
```

Or just [search nostr.band on the web for "matt"](https://nostr.band/?q=matt%20kind:0) and see how many results there are.

It looks like local search is working, as seen in the video above. There seems to be an issue with the relay search, or displaying results from it, or something along those lines.

Sometimes the results do eventually appear, but it seems to take a very long time.

**Comment by joshuatbrown** [comment]
This seems to have stopped happening for now, so I'm moving this to the backlog.

**Comment by setch-l** [comment]
@joshuatbrown - Is this still an issue you are seeing? Should we add something to indicate there is a slow network connection and search isn't available? As I think that was the thing that was happening. Is that detectable in the app?

**Comment by joshuatbrown** [comment]
@setch-l I can't reproduce it today. I think I may have seen recently, but I don't remember for sure.

**Comment by joshuatbrown** [comment]
@setch-l I believe #1466 fixed this issue, so I've moved it to UAT.
