### ISSUE TITLE
[Post Preview] Adding a Post Preview toggle to the editor

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1399]
This ticket contains three stories:

**Add preview post toggle to editor**

Given that I am a user of Nos
When I creating a post or a reply 
Then I should see a Preview Post toggle in the editor tool bar. 
Note it will be disabled while an image is uploading

Designs: 
See the 6 & 7th screens of the is workflow: https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7554-3294&t=x6jIcwUAS231BUBJ-1

**Toggling the preview post on**

Given that I am a user of Nos 
When I toggle preview post to on 
Then I should see the following: 

- A post header tool bar with cancel and Post to all my relays options
- A preview of the post 
- The editor tool bar with the preview post turned on and nothing else 

Designs: 
See the 9th screen in this workflow: https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7554-3294&t=x6jIcwUAS231BUBJ-1

**Turning off the preview post toggle** 

Given that I am a user of Nos viewing the post preview
When I toggle the preview off
Then I should return to the editor so I can continue editing my post

Designs: 
See the 7th & 8th screens: https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7554-3294&t=x6jIcwUAS231BUBJ-1

**Comment by mplorentz** [comment]
I started this on one of my plane rides actually. I can finish it next week when I get back but I will also add a comment later today pointing to the work I've done so far in case @martindsq wants to finish it while I'm gone.

**Comment by mplorentz** [comment]
I've pushed my work up for this to the branch named `note-composer-preview`. It mostly works, although the UI isn't quite right. The tricky part is that NoteCard wants an Event, so we have to create an Event while showing the preview and be careful to delete it afterwards.

Remaining TODOs off the top of my head:
- fix styling
- make sure preview Events are deleted when the preview is hidden
- detect and clean up any Events used for previews in DatabaseCleaner, as a failsafe. Their `identifier` is "preview" so they can be easily found.
