### ISSUE TITLE
Hide wss:// in relay list / editing

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#1401]
## Describe the bug
All relays are wss or ws and so we should hide that part of the url the way browsers hide the http until you copy it. 

## To Reproduce
1. Go to to the relay list
2. Tap text area to add a new relay
3. Enter relay without wss://
4. See relay list displayed jsut domains not wss:// or ws:// part

## Expected behavior
Able to add and view relays without displaying the wss:// part

**Comment by lingoslinger** [comment]
@joshuatbrown  I would like to take a stab at this one if no one else minds...

**Comment by joshuatbrown** [comment]
I do have one concern about this: if we decide to support insecure relays (`ws://`) in the future for local development (with something like `nak` which now supports running [a local server](https://github.com/fiatjaf/nak?tab=readme-ov-file#run-a-somewhat-verbose-local-relay-for-test-purposes)), there's no way to show the full relay URL. Maybe this is something devs will just have to deal with, or maybe it's something to deal with later if/when we allow `ws://` relays.

**Comment by lingoslinger** [comment]
Removing ws:// is simple enough but it looks like adding an insecure relay would involve diving into existing error logic. Let me know if we decide that the insecure server support should be handled now or later.

**Comment by joshuatbrown** [comment]
@lingoslinger don't worry about it now; I just wanted to point it out for later. Thanks again for working on this!
