### ISSUE TITLE
[Design] Onboarding competitor research

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1405]
We need to create a new onboarding workflow for Nos. While we spend some time on user research to figure out what we want to onboard people into, we can take a look at onboarding workflows that really work across the app space. 

Deliverables
- Document 3-5 onboarding workflows for installed applications (not web apps) 
- 1-2 of them should be outside the social media space, bonus if it's more... 
- ID on the workflows patterns that you enjoyed vs those that felt cumbersome or intrusive.

**Comment by Chardot** [comment]
Here's the [onboarding research file on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8197-114&t=WvjFtDo2BQREF87w-1).

For evbery app, I recorded an onboarding session, noted down its duration, and marked the screens where there was something that captured my attention:

![Image](https://github.com/user-attachments/assets/5707aa01-5e8e-4024-b919-15c4a85bc85c)

Then I proceeded to identify all the UX and UI patterns and grouped them. I added a star to the patterns that I'd like to use in our future onboarding design:

![Image](https://github.com/user-attachments/assets/1801d122-efc4-4460-b0b1-6fae79384746)

and prepared slides for each pattern along with a brief description to present:

![Image](https://github.com/user-attachments/assets/fb5457fc-e24f-4b54-8b82-5f07d0d16974)
