### ISSUE TITLE
[Design] Design a workflow for account deletion

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1428]
Overview: 
In order to launch we need to support Account deletion. The assumption is that when a user deletes their account, we will also send a delete request for all their notes across the relay service. 

AC 
- Look at Damus, Primal, OpenVibe to see how they handle this today or other non-Nostr apps
- Create wireframes for the workflow making sure users understand
- Their notes will also be deleted 
- Their private key will be deleted and will not work in the future 
- Share workflows with Linda 
- Share in Design Review 
- Make final designs for dev ready

**Comment by Chardot** [comment]
I designed a [user flow for permanently deleting an account](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8491-13476).

![Image](https://github.com/user-attachments/assets/27c913da-c5b1-4f14-aab7-e01e3a92f768)

@setch-l please let me know if I should modify the copy on the warning and confirmation messages. For what I understand, we can't ensure that the notes and replies posted by the user will be effectively deleted from every relay we request it. Those will be deleted from our relay for sure. Should I be more specific about this in the warning and/or confirmation text?

![Image](https://github.com/user-attachments/assets/3626aca3-7105-4a72-8cd7-b7d6384708b1)

[Here's the link to these designs on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8531-15083&t=tXk0JPzb6pHz7fe9-1).

**Comment by Chardot** [comment]
@rabble Could you type your suggested copy for this screen here?

**Comment by Chardot** [comment]
After reviewing the flow and copy changes with @setch-l, here's the final version with visual design applied:

![Image](https://github.com/user-attachments/assets/72befc4d-e73e-45a4-9ec2-b4fe0a47a883)

Here's the link to [these designs on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8491-13476).
