### ISSUE TITLE
[n things] Dropping in a url + naddr event does weird things in our app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1429]
Steps to reproduce: 
Create a post with this link in Nos
https://yakihonne.com/notes/nevent1qgszpxr0hql8whvk6xyv5hya7yxwd4snur4hu4mg5rctz2ehekkzrvcqyrej80hs0k7ydd60p4zpdddqlx4zr66fwns5frwn2zf2gg3u8vr3w725fc0

Here's an example ID you can check out: note105c24z97glcwptdgm4feevczvpv8smrthktvsfwk5gac6rqwt4kq5xvyca

![Image](https://github.com/user-attachments/assets/b9d22f10-8344-43b9-bc4a-e3af7ac3bdd7)

Then view the post in Damus and Yakihonne. 

![Image](https://github.com/user-attachments/assets/8854b522-328d-466d-b959-64c373a8e5f7)

Issue: In Nos we render some of the text etc, but in Damus and Primal they simply display the link for the user to click through. 

This is an easy fix for getting smart widgets to be clickable in Nos. However I'm curious if it would break something else we implemented previously. 

They are planning to publish a NIp about these later this week as well...

**Comment by setch-l** [comment]
Hi @bryanmontz - This is what I'm seeing on staging build 427. 

![Image](https://github.com/user-attachments/assets/1c90b04e-a3fb-4d79-b2c7-82ccb87c8884)

**Comment by bryanmontz** [comment]
@setch-l Sorry, I don't understand what you're saying. On Test Cal Account's profile, I see the yakihonne note as expected (I believe):

<img src="https://github.com/user-attachments/assets/b005768b-078b-4613-9b1c-7badc0307bb4" alt="image" width="340"/>

**Comment by bryanmontz** [comment]
@setch-l Could you try this one again please? It seems to work as I expected.
