### ISSUE TITLE
[Sentry] Investigate what sentry reporting we can add for critical areas of the app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1448]
We have identified the following critical areas of the app: 
- Content loading
   - https://github.com/planetary-social/nos/issues/1635
   - https://github.com/planetary-social/nos/issues/1649
- Profile information and content loading
   - https://github.com/planetary-social/nos/issues/1647
- Smooth scrolling
   - Sentry doesn't have any direct support for tracking scroll performance. They do offer some integration with MetricKit which is the way Apple collects performance data, but it has some bugs and we should be able to get the same data on this [from Apple](https://developer.apple.com/documentation/xcode/analyzing-the-performance-of-your-shipping-app) after we launch. 
- Tagr Bot tags individual posts not accounts
   - We investigated this bug in https://github.com/planetary-social/nos/pull/1475/files and since we can't reproduce or understand it we can't write code to detect it. The next step here is to get someone's logs the next time they see it.
- Human tagged posts and accounts works correctly
   - This seems best accomplished through manual testing. The only way to automatically test this would be to set up an end-to-end UI test and we'd need to build out a lot of scaffolding to make that work. Happy to discuss further.
- Lists are not wiped including follows, relays, mute
   - We have an [alert](https://grafana.planetary.tools/alerting/grafana/ca88de0f-c86d-42d1-99e1-3bf01bc4ba78/view?returnTo=%2Falerting%2Flist) set up in the followers server if Nos deletes a follow or relay list. [Here](https://github.com/planetary-social/nos-followers/issues/32) is a ticket for the followers server to start tracking mute list. This may be more complex than it seems because the follows server currently only deals with follow lists.
- People can log in and content and info loads in a reasonable amount of time
   - Our app's [launch time](https://developer.apple.com/documentation/xcode/reducing-your-app-s-launch-time) will be available in the Xcode Organizer after we launch. This tracks the time our app spends starting up. [Sentry can also track this](https://docs.sentry.io/product/insights/mobile-vitals/app-starts/) but it requires a Business or Enterprise plan, so I suggest we try the free metrics first. For time to first content see below.
   - https://github.com/planetary-social/nos/issues/1650
- New accounts see activity in the app it doesn't look dead or empty
   - https://github.com/planetary-social/nos/issues/1650
Note these last 2 encompass content loading, profile loading & lists. Are there other things beyond those we need to be away of in these scenrios? 
   - I don't see any other critical app performance/correctness risks around the first login. We'll obviously want to pay close attention to the analytics for these sessions to see when/if people are dropping out of the funnel. 

We need to ID sentry tracking for each of these critical areas of the app experience so we can easily identify when something has gone wrong. 

Acceptance Criteria 
- List in the ticket recommendations for sentry tracking for each of the 6 critical areas of the app and any bonus things we should track for logging in or creating a new account. 
- Create individual tickets for each tracking task and label it [Sentry] in the title.

**Comment by mplorentz** [comment]
I was able to spend a little bit of time on this on Friday and Monday. After reading through the docs and looking at the automatic transactions Sentry is capturing I think it's best to turn off automatic transaction recording [docs](https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/automatic-instrumentation/). Sentry only records transactions for UIKit view controllers, which we don't use much, and it appears that a lot of the data it collects is misleading. For instance it starts a [transaction](https://sentry.nos.social/organizations/verse/performance/summary/?project=2&query=&referrer=performance-transaction-summary&statsPeriod=7d&transaction=UITabBar._sendAction%28withEvent%3A%29&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29) when the user taps the Home tab but it doesn't complete it when the home feed displays data.

We should set up [custom instrumention](https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/custom-instrumentation/) as described above.

We should add comprehensive [breadcrumb](https://docs.sentry.io/platforms/apple/guides/ios/enriching-events/breadcrumbs/) tracking to help us understand and reproduce performance issues.

Now that I understand more about how Sentry uses transactions, spans, and profiling I can start going through each of the cases above and see which can be measured by Sentry's tools.

**Comment by mplorentz** [comment]
Here are the first few tickets I created.

https://github.com/planetary-social/nos/issues/1632
https://github.com/planetary-social/nos/issues/1633
https://github.com/planetary-social/nos/issues/1635

**Comment by mplorentz** [comment]
@setch-l I've filled out the ticket description with my proposal for tracking all of these, and moved the ticket to UAT for your review. Let me know if you have any concerns. Happy to talk about any of these in more detail either here or in a meeting.
