### ISSUE TITLE
[Bug] Text is replaced when composing a note on Mac

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1460]
When trying to compose a note in Nos for Mac the text often gets replaced even when there are no typos. See video:

https://github.com/user-attachments/assets/13c07edb-5db0-4c77-94d1-b11b18e791d9

**Comment by setch-l** [comment]
Spoke to Bryan about this and he thinks this is a Mac issue - either a user setting or OS version.

**Comment by setch-l** [comment]
See if we can disable auto-complete for either Mac or iPad or both. Linda will check if it also happens on iPad.

**Comment by setch-l** [comment]
@bryanmontz - Auto-complete works fine on the ipad but not the mac. I would time-box this bc we don't have that many users on the ipad / mac app at this point.
