### ISSUE TITLE
Some quoted notes are rendered offscreen

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1463]
Steps to reproduce:
Open this note on an iPhone (15 Pro) https://njump.me/note10khgjczqvs78ad8kshksalkfqmuylz9x2fsvphfvye0j7ff67v2se778eq

Expected: the quoted note fits on the screen
Actual: the text flows off the right side

<img src="https://github.com/user-attachments/assets/def0db05-d250-4ffd-a3d0-e0ddf7c94913" width="300" />

Observed on 0.1.26 (427)

**Comment by tedbrosby** [comment]
Hi Nos Team, 
I wrote a PR with a fix here: 
https://github.com/planetary-social/nos/pull/1470

**Comment by mplorentz** [comment]
Thanks so much @tedbrosby!
