### ISSUE TITLE
relay metadata is never updated after initial save

### ISSUE THREAD

**Issue by bryanmontz** [planetary-social/nos#1472]
## Describe the bug
Faulty date logic is preventing relay metadata from ever getting updated after the first time it is requested and saved.

## To Reproduce
The user cannot directly observe this issue, but some logging at the right spot reveals the issue:

In `RelayService.queryRelayMetadataIfNeeded(_:)`, add the log statements, run the app, and observe the console:
<img width="827" alt="Nos_—_RelayService_swift" src="https://github.com/user-attachments/assets/3b4d023e-8df0-47ed-a1ed-4c9053e530dc">

During this run, the breakpoint is never hit. It should be hit because 4 of the 5 relays have metadata old enough that they need to be updated (about two weeks old).

## Expected behavior
Relay metadata should be updated when its age is above the 3-day threshold.

## Technical info
 - All devices and environments

**Comment by tedbrosby** [comment]
Hi Bryan, I took care of this here: 
https://github.com/planetary-social/nos/pull/1478
