### ISSUE TITLE
Search results are not sorted properly

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1485]
## Describe the bug
Our search results are not always sorted by the number of known followers.

## To Reproduce
1. Launch Nos with an account that follows a good amount of people
2. On the Discover tab, search for someone that a lot of your followers follow. Type slowly.

## Expected behavior
The results should be sorted by the number of known followers. We display this data in the message "Followed by x, y, and z others" at the bottom of the result cards. Sometimes they are sorted correctly and sometimes they aren't.

## Screenshots or Video

https://github.com/user-attachments/assets/d56c6bec-959b-4b32-9872-7babc742bb8d

## Technical info
 - OS: all
 - App Version: 0.1.27 (439)
 - Environment: Staging

**Comment by joshuatbrown** [comment]
@tedbrosby that's fine with me! I'll assign it to you so we can track it -- thanks!
