### ISSUE TITLE
[Moderation workflow] New flag user flow

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1493]
Parts of this flow will be implemented in #1498 #1499, etc. but this ticket is to make sure we test and complete the entire flow for flagging a user.

Given that I am a user of Nos
When I click Flag user from the 3 dots menu on a user profile
Then I see the following Flag user screen: 

Header: cancel | Flag User | Send button (Deactivated)

Create a tag for this user that other
people in your network can see.

[5 options]

Spammer 

Harassment & Profanity 
(description) 

NSFW
(description) 

Illegal 
(Description) 

Impersonation 
(Description) 

Other 
(Description)

**Comment by mplorentz** [comment]
@setch-l @Chardot the current Flag User flow includes the option to mute the flagged user after reporting them. I don't see this included in the Figma designs. Should we add another section for this?

**Comment by Chardot** [comment]
@mplorentz @setch-l I updated the flow and added the Mute User option as the last step in the account flagging form. Here's a link to the [updated design in Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8517-13793&t=YawfvFUR0AnJ4Noe-1).

![Screenshot 2024-09-11 at 19 39 57](https://github.com/user-attachments/assets/544b58a5-9739-4a6f-ba06-4e4005e7b553)
