### ISSUE TITLE
[Design] Separate WOT notifications from non WOT notifications

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1536]
For a subset of users who receive a lot of notifications it can be hard to distinguish WOT notifications from those that are not WOT. 

**What problem are you trying to solve?**
Rabble has too many notifications. It's also a temporary solution for unwanted, harrassing notifications as well as spam. Idea 8 is the best solution for this work. 

**What value would it provide if solved?**
Mostly making the top 1% of users lives easier. Possibly making the lives of people who do not want to see out of network notifications easier. (Again Idea 8, may be a better solution for this). 

**Target outcomes**
Users can view WOT and non-WOT notifications separately in the notifications tab.

**Comment by rabble** [comment]
This is needed but not “today” urgent because the spammer has paused his scripts. 

https://njump.me/note159dc9eccy6wfrz7fcs0kaytuupwvar89hts2wg20a0rax6lm7dls6zq0zc

**Comment by Chardot** [comment]
I'm proposing we split the Notifications screen in two tabs:

- Friends of Friends
- Out of Network

where only the notifications of friends of friends count in the badge on the Notifications tab.

Here's the basic user flow for navigating notifications:
![Screenshot 2024-09-24 at 18 16 35](https://github.com/user-attachments/assets/18b73c5e-e85d-4284-9c73-1c1be9826f5b)

You can see these [designs on Figma here](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9057-26808&t=UXIFheCCmsG7kyMs-1).

**Comment by setch-l** [comment]
Hi @Chardot - Let's add a third tab to this for Follows and then call it done. 

So it would be: Follows | In Network | Out of Network
