### ISSUE TITLE
[Design] Create a phase 1 onboarding workflow

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1537]
We did a card sorting exercise to determine what was the most important things new users to Nostr wanted to understand / learn during onboarding. Based on the feedback and our product trio exercises, put together some sketches for a basic onboarding for users. 

Reference the frames in this Miro: https://miro.com/app/board/uXjVNyrg4Kk=/
Public / private key text: https://www.notion.so/nossocial/Public-Private-Key-Explainer-Text-10a7c4703da0804c878ec90b33f5366c?pvs=4

Create a sketch using the fewest number of steps from the miro board workflows. 
Share it with the product trio 
Make updates
Share at design review 
Updates
Final comps

**Comment by Chardot** [comment]
### Wireframes
Here's a link to the [3 revisions of the onboarding flow](https://www.figma.com/design/9U8xJlfBllvblDVN2FAFK0/Work-Sheets?node-id=3-335&t=UF66tCaBiCWbv2Lc-1) wireframes.
![Image](https://github.com/user-attachments/assets/f9533d30-1478-4a4c-aebe-8584a9aa7b8a)


### Visual Design
I applied visual design to the third revision, and [here's a link to it on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9221-8504).
![Image](https://github.com/user-attachments/assets/b717d9c8-d64a-4cc9-b89b-f4af9843b17e)


### Prototype
[This is the link to the clickable prototype](https://www.figma.com/proto/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9321-17071&node-type=frame&viewport=2693%2C1247%2C0.29&t=l1mqoiTfRSCpnOEQ-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=9321%3A17071) of the new onbaording flow.
![Image](https://github.com/user-attachments/assets/1543f7ef-e854-450c-911f-31006800685e)
