### ISSUE TITLE
Support autocomplete of user mentions when composing a note

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#155]
Let's autocomplete username when the user starts typing `@` when composing a message (whether root or reply). We want the behavior and UI to be similar to Planetary, ~~but let's try basing the code off [this](https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-a-search-bar-to-filter-your-data)~~. For now let's just make the autocomplete list all authors we have in Core Data.

**Comment by mplorentz** [comment]
I met with @martindsq and @Chardot separately to discuss the design for this. The summary of those discussions is that we want the UI to match the way Planetary did it circa `43dc53e2` with the following changes:
- when typing an "@" we show the autocomplete results and we continue showing autocomplete results until 1) the user taps on a name to autocomplete it 2) there are no results for the given string or 3) the user hits the spacebar twice. 
- the autocomplete window should always be displayed towards the bottom of the screen near the top of the keyboard, not at the top like it is in Planetary's thread view. 
- Make sure the autocomplete windows does not prevent the user from scrolling to the bottom of a thread in the thread view.

@Chardot is working on a quick design for this.

**Comment by rabble** [comment]
This also needs to work when a user pastes in the full npub / nprofile in to the note text box.

**Comment by Chardot** [comment]
> This also needs to work when a user pastes in the full npub / nprofile in to the note text box. ![9B1BDC3D-7BA7-42B9-851A-DD395F23AE93](https://user-images.githubusercontent.com/76/235284573-b7e7076b-7f8b-45d4-aa76-c294f0162074.png)

I think this deserves its own issue for displaying long links (weather it's for notes, profiles or any URLs). I'll create one

**Comment by mplorentz** [comment]
@mplorentz is going to port the current UI to the RepliesView
