### ISSUE TITLE
[Design] Update the follows notification design to reflect the latest styles in the app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1554]
The follows notification design in Figma is out of date. Please update so it reflects the following styles that exist in the rest of the app: 
- check mark follows and + signs are on the profile image
- time stamp is on the right. 
https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=5791-22588&t=Vkc2LWq8KmXWxym3-1

**Comment by Chardot** [comment]
I updated the Follows Notifications screen (soon to become the first of three tabs in this screen) with the current styles in the app, plus big user avatars and floating follow/following buttons inherited from the Discover screen.

![Screenshot 2024-10-01 at 16 52 40](https://github.com/user-attachments/assets/1a392d85-1429-4f4e-b52d-653cff0f8cf1)

Here's the [link to this design on Figma](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9353-825&t=QCYapKs5LIevE6Ci-1).
