### ISSUE TITLE
[Autocomplete] Search relays during mentions autocomplete

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1560]
Currently the search function that powers our autocomplete of user mentions only searches Core Data locally. It should also search the relays in the user's relay list (and nostr.band). This fulfills the last part of the following [user story](https://docs.google.com/document/d/1O32cxqTpPvQ_7pJafO0US8P6S-eDdXNpEbl0ognZS3I/edit):

> Given that I am a user of Nos 
When I click the @ symbol in the editor 
Then it should place an @ in the editor AND 
Display the people in thread. 
AND 
The rest of the search should take place across the network. 

Note: This ticket does not include the change to prioritize people participating in the thread at the top of the search results.

# Implementation

We have already implemented searching for users by name on our Discover tab. This implementation uses a `SearchController` with a simple interface. The view set the `query` to the string the user is searching for and the `SearchController` populates the `authorResults` array with the results that should be displayed in the view. The current autocomplete UI uses `AuthorListView.search()` to build the list of search results from Core Data. Refactoring `AuthorListView` to use the `SearchController` is a good starting point for this ticket.

**Comment by rabble** [comment]
Make sure you also take in to account #1568 and that the mentions are sorted in order of engagement on the thread first and secondarily based on the number of mutual contacts with that person.

**Comment by mplorentz** [comment]
@rabble oh I didn't know about that ticket and filed a draft ticket that for this same thing. Thanks for linking the existing one.  I moved it into the sprint.
