### ISSUE TITLE
[Autocomplete] Add participants in a thread to the mentions lookup

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#1568]
As a user of Nos making a reply to a thread, the mentions dialog box should be preloaded and always include everybody participating in that thread even if they’re not one of your contacts. When sorting mentions, the participants in the thread should be listed ABOVE the others who are not active in that thread and sorted by mutual follows. The people active in the thread should be loaded before any letters have been written to search for a specific person. Once the user starts searching, then the search filter should be applied to the participants of the conversation. 

This should make it much easier to know that you’re @mentioning the right person in the thread, and encourage mentioning people which increases engagement. 

This fulfills the following [user story](https://docs.google.com/document/d/1O32cxqTpPvQ_7pJafO0US8P6S-eDdXNpEbl0ognZS3I/edit)
>  When I click the @ symbol in the editor 
Then it should place an @ in the editor AND 
Display the people in thread.

**Comment by pelumy** [comment]
@rabble  to clarify the statement below:

> the participants in the thread should be listed ABOVE the others who are not active in that thread and sorted by mutual follows

What do you mean by "**participants in the thread who are not active**"? Is this participants in the thread with the **lowest** amount of replies or participants in the thread with the **older** reply dates?

cc: @setch-l, @mplorentz

**Comment by setch-l** [comment]
@pelumy - I'm guessing here but I suspect "not active in the thread" refers to other people you follow. So the order would be: 
- Mutuals active in the thread
- Non-mutuals active in the thread

**Comment by mplorentz** [comment]
There's a lot of complexity here and @pelumy and I just spent a while diving into it. Here's where we arrived:

**Who are the participants in a thread?** The participants include the authors and anyone mentioned in:
1. The note being replied to (call it note A)
2. The root note of note A (the note it was replying to, if any)
3. Any replies to note A (maximum 10, for performance reasons)

Fetching more than this is problematic from a technical perspective, but I think everyone will be happy with how this behaves. If not let's discusss further.

**Comment by pelumy** [comment]
Got on a call with @setch-l  and @joshuatbrown today. We decided to start by displaying only the authors in the thread and the users mentioned in the note being replied to. To avoid performance issues, we won't be implementing mutual follows sorting at this time.
