### ISSUE TITLE
Update the discover tab categories and accounts for launch

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1592]
Update our discover tab to match the latest accounts and categories specified [here](https://docs.google.com/document/d/1VP65TppqtnesGiMgxV384evs1DYjmB1Y72b0OUAj6cU/edit).

AC - 
- Remove inactive people 
- Add new categories 
- Put the categories in Alphabetical order 
- Add new people to All, New, their respective categories

**Comment by mplorentz** [comment]
@setch-l should we treat these new accounts as cohort 5 or are we done with cohorts (they are organized in cohorts in the code, just trying to figure out if we should keep it that way if there will be more cohorts)?

**Comment by setch-l** [comment]
yeah you can treat it as cohort 5
