### ISSUE TITLE
[Onboarding] Update existing TOS screen and add Privacy Policy

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1593]
### Update existing TOS page & add Privacy Policy check box 

Given that I am a user of Nos 
When I view the login / try it screen
Then I should see a notification that moving forward i accept both the TOS and Privacy policy. 

Designs:
https://www.figma.com/design/6MeujQUXzC1AuviHEHCs0J/Nos---In-Progress?node-id=9549-628&t=Ygh3Do6NVmRiGVfi-4

Link to TOS is https://www.nos.social/terms-of-service

Link to privacy policy is https://www.nos.social/privacy

**Comment by joshuatbrown** [comment]
Matt has some questions [in the Figma design](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9321-17099&t=d296j9gCZ5VIm7nC-4) that impact the implementation of this; I'd like to wait to start until those are sorted out.

**Comment by joshuatbrown** [comment]
[The Figma design](https://www.figma.com/design/6MeujQUXzC1AuviHEHCs0J/Nos---In-Progress?node-id=9549-628&t=Ygh3Do6NVmRiGVfi-4) has been updated, so I think we're good to go.

**Comment by mplorentz** [comment]
I found an issue this morning that was introduced with the PR for this ticket. The tab bar and empty home screen are displaying for a split second before onboarding.

https://github.com/user-attachments/assets/d618f52e-4ce5-4694-b2bc-11dcc2702fae

I'm going to bounce this back to In Progress so we can get it fixed.
