### ISSUE TITLE
[Onboarding] Go to Your Feed tip

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1601]
### Feed tooltip appears 

Given that I am a first time user of Nos
When I have followed 3+ accounts more than the ones I auto-follow on sign up
Then I should see a tool tip that reads:

Go to your feed to see notes from your connections. 

https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=9321-32503&t=2pL8XQ9xMZk2F2zZ-1

**Comment by joshuatbrown** [comment]
This was a challenge to implement as designed. I thought we'd be able to have the bottom left corner of the bubble point down at the Feed button, but I wasn't able to get that to work. If we spend more time on it, maybe we can get it, but for now I'd recommend we either push this off and focus on the other onboarding tickets, or redesign it so there's no down-pointing arrow to something more like this (with or without the emoji):

![Image](https://github.com/user-attachments/assets/2fa4744b-b4fc-424f-9c83-07f154ec9c06)

**Comment by setch-l** [comment]
@joshuatbrown - Ok - I think I misread your comment the other day. I think using the emoji is fine for now. Again this is somewhat of a placeholder and it's important to keep the user in the onboarding flow so they make those first few connections with others in the app.

**Comment by joshuatbrown** [comment]
@setch-l I'll continue moving forward with the code that shows the above screen shot. Just need to set up the rules around when to display it and when to dismiss it.

**Comment by joshuatbrown** [comment]
@setch-l This doesn't look great on iPad in landscape, so I want to check and make sure it'll be acceptable, at least for now:

![Simulator Screenshot - iPad mini (6th generation) - 2024-10-16 at 15 02 56](https://github.com/user-attachments/assets/7cd9d154-82fa-46a1-9cc3-d2ece37ece09)

**Comment by setch-l** [comment]
@joshuatbrown - That looks amazing. It's fine. We have a lot of looonnnnnggggg things ont eh ipad.
