### ISSUE TITLE
[Onboarding] Welcome to Your Feed tip

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#1602]
### New users arrive on the feed for the first time

Given that I am a user of Nos
When I view the Feed tab for the first time
Then I should see a tool tip at the top of the feed 

Designs: 
https://www.figma.com/design/6MeujQUXzC1AuviHEHCs0J/Nos---In-Progress?node-id=9321-36718&t=mhdw7km88kruVbWh-4

### Dismissing tool tips 

Given that I am a user of Nos 
When I dismiss a tool tip 
Then it closes and on the feed screen the notes slide up.

**Comment by joshuatbrown** [comment]
@setch-l as currently implemented in my open PR, this Welcome tip will appear for _all_ users when they first land on the feed. That includes anyone who's been using the beta, and anyone who signs in with an existing key. Will that be a problem?

**Comment by setch-l** [comment]
Hi @joshuatbrown - If it is a one time display, then no I don't think it will be a problem to show it to everyone once. If it happens everytime someone visits the feed on app re-open re-launch, then i think we should talk about the options.

**Comment by joshuatbrown** [comment]
@setch-l Thanks! It'll only display once and stay until the user taps the 'x' button to dismiss it.
