### ISSUE TITLE
[Design] Create screenshots for the app store

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1624]
We need both iPhone and iPad screenshots for the app store: 

Screen 1: Discover tab (newer version - need to wait for Itunu for this one) - Nos puts you in control of what you see. 
Screen 2: Feed - See notes only from people you follow 
Screen 3: Editor - Share your thoughts, art and more via Nos
Screen 4: Content moderation - User led moderation allows people to customize what they do and do not want to see

**Comment by Chardot** [comment]
@setch-l Here's all the app screenshots in the 3 required sizes (all other sizes are generated from these):

![Image](https://github.com/user-attachments/assets/f4b18d11-b02a-4abb-b8cb-44d972dc7bf7)


- [6.5 inch iPhone](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11205-13&t=fTEsBSc2JqRBc8kr-1)
- [5.5 inch iPhone](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11205-940&t=fTEsBSc2JqRBc8kr-1)
- [12.9 inch iPad](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11210-204&t=fTEsBSc2JqRBc8kr-1)

There are a few details to fix, like making sure the date and battery charge in the status bar is similar across all screenshots. But the most important thing is to make sure the content we show in these screenshots aligns with a communication strategy.

For example: do we want to show any note in particular or content from a specific account in the second screenshot (Feed)? Do we want the third screenshot (editor) to show any content in particular?

The title on the first screenshot "Nos puts you in control of what you see" seems to talk about the same as the fourth one "User led moderation allows people to customize what they do and do not want to see", but the first title goes above the Discover screen where we show creators. Don't you want to change that first title to something related to discovering creators?

Something like this:
![Image](https://github.com/user-attachments/assets/7025db23-e613-4cb7-8905-2e5b4822484a)

**Comment by Chardot** [comment]
Here's the set of wallpapers I created for iPhone and iPad:

<img width="982" alt="Screenshot 2024-10-22 at 14 47 42" src="https://github.com/user-attachments/assets/b147a242-8409-4306-8e30-d8e1cc7f54de">

### iPhone

- [6.9 in](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11240-647&t=PSkJjyTnyXWYn08k-1)
- [6.5 in](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11225-47&t=PSkJjyTnyXWYn08k-1)
- [5.8 in](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11247-899&t=PSkJjyTnyXWYn08k-1)
- [5.5 in](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11240-381&t=PSkJjyTnyXWYn08k-1)

### iPad

- [Portrait](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11234-36&t=PSkJjyTnyXWYn08k-1)
- [Landscape](https://www.figma.com/design/XM21evtqKhVBdToM59Gh8I/Nos---Branding?node-id=11225-447&t=PSkJjyTnyXWYn08k-1)
