### ISSUE TITLE
Support reposts

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#205]
Let's add a button to NoteCards that allows us to repost them. We should also show a notification in the notifications tab when one of your posts is reposted or replied to.

**Comment by mplorentz** [comment]
@Chardot I think we need design for this. I added a `needs design` label, but let's talk if there's a different way you would like to see that on the board.

**Comment by Chardot** [comment]
@mplorentz Here's my proposal:

![Image](https://user-images.githubusercontent.com/477835/233440793-3e7d455c-4c3c-45af-b0d0-38f257f9ffaa.png)

[Link to frame on Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?node-id=981%3A13432&t=1ARuaPdO5Pkr32WP-1)
