### ISSUE TITLE
Add support for relays starting with `ws`

### ISSUE THREAD

**Issue by ademers** [planetary-social/nos#228]
I, and many others, are running a private Nostr relay on our Umbrel node. Fo us to be able to connect our Nostr clients to our relay ~~from anywhere (not just home network), we need to run Tailscale on our Umbrel & devices and use~~ `ws://umbrel:4848` or `ws://umbrel.local:4848` as the URL in our Nostr clients. See readme at https://github.com/getumbrel/umbrel-nostr-relay

For my own understanding, would this involve adding an OR operator to https://github.com/planetary-social/nos/blob/595594e5ddb40e9991d6ebd99cc03879518e52c6/Nos/Models/Relay%2BCoreDataClass.swift#L100. Or, is there more to it. Thanks!

**Comment by mplorentz** [comment]
Hi @ademers! Unfortunately there is a bigger difference between ws:// and wss:// which is SSL security. Talking to a relay over `ws://` is like talking over `http://`, it opens your communication up to man in the middle attacks and snooping.

That said we should probably make an option for this, especially if many users are deploying relays without SSL certs via Umbrel. I'm not sure how soon we'll get to this but I'm putting on our board to be prioritized.

**Comment by mplorentz** [comment]
After some discussion we have decided not to support unencrypted relay connections. Hopefully you can find another app that allows you to do this!
