### ISSUE TITLE
Design production UNS integration

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#230]

**Comment by Chardot** [comment]
This is the flow that I'm proposing:


![Image](https://github.com/planetary-social/nos/assets/477835/3dc5cb98-1f9b-4e5b-8314-7a2b22b9ecdd)


I still need to design the additional screens explaining the reason why a name might be unavailable, along with the actions that can be taken.

**Comment by rabble** [comment]
We need to work with UNS to handle issues where the user already has a account with that phone number, or when the name is a premium name or trademarked. @Chardot there's more design needed. @mplorentz we probably need new API calls for this.

And we need to talk to them about the contact list upload.

**Comment by Chardot** [comment]
@mplorentz and I met to discuss the updated registrarion flow, and this was our conclusion:

![Image](https://github.com/planetary-social/nos/assets/477835/a9a4d76f-0b15-4848-82f0-933afca22545)

and here's the 95% progress on the design:

![Image](https://github.com/planetary-social/nos/assets/477835/4ca504c2-72f1-4974-8484-412723a53271)

I still have to design the graphics for the 3 cards in the wizard, and the graphic for the Premium Names screen at the end.

[Here's the entire flow on Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=2644%3A8203&mode=design&t=vycHqccyX7hZSjm8-1)
