### ISSUE TITLE
Liking a note does not work

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#258]
As a user, I want a note to be «liked» right after I tap on the Like button, so I feel that my action was captured and that the app is responisve.

In the following video I'm tapping multiple times on the Like button at Cameri's first note on my feed:

https://user-images.githubusercontent.com/477835/233455485-2dafd285-d46d-4ade-8c55-a6d069ef3412.MP4

**Comment by rabble** [comment]
![Screenshot 2023-04-29 at 5 07 55 PM](https://user-images.githubusercontent.com/76/235284649-3a648f44-1cba-4fc7-821c-74f8ec1353f5.png)


Needs to support nostr: links as well as @nnote links.

**Comment by mplorentz** [comment]
@Chardot I think this is fixed. Can you test on the latest testflight?

**Comment by mplorentz** [comment]
> Needs to support nostr: links as well as https://github.com/nNote links.
@rabble I think you misread this ticket as being about "linking" when it's actually about "liking".
