### ISSUE TITLE
Hackathon T-shirts

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#266]
As a winner of the hackathon, I want a beautiful Nos t-shirt, so I can wear it at conferences and events and spread awareness about this awesome app!

**Comment by Chardot** [comment]
These are the designs. I'm cleaning up the vector file so that it prints correctly with any technique.

![Image](https://github.com/planetary-social/nos/assets/477835/b27146fe-3a1f-4734-8b28-bdb7440c529b)



![Image](https://github.com/planetary-social/nos/assets/477835/9bc75d85-8ea0-49a8-8261-f0f2b734d6d4)



![Image](https://github.com/planetary-social/nos/assets/477835/aa65eb1a-ebc5-4d1a-a45b-d97cc4137d07)



![Image](https://github.com/planetary-social/nos/assets/477835/ae833db9-0e4f-46e0-9434-9e66fad86fb5)



![Image](https://github.com/planetary-social/nos/assets/477835/9f238297-24a8-4c46-bba8-0e871a015ac0)

**Comment by mplorentz** [comment]
@Chardot will talk to Shaina about scheduling this.

**Comment by sathomp** [comment]
Bulk order has been placed. Tshirts will arrive Aug 8th

**Comment by sathomp** [comment]
Bulk order arrives tomorrow. Will need to divide and check for addresses in nos account

**Comment by sathomp** [comment]
Actively reaching out to winners to provide updates and get shipping info. 1 week timeline.

**Comment by sathomp** [comment]
mailing out to those whose addresses i have on Friday

**Comment by sathomp** [comment]
Tshirts mailed out to few Participants who provided addresses.  

Team shirts mailed to Matt in Indiana, scheduled to arrive on Wednesday Oct 10. He will bring to Japan.
