### ISSUE TITLE
Fix code to republish events that failed to publish the first time

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#274]
The app prints a lot of these messages:
```
0 relays missing a published event.
```

This comes from the RelayService.publishFailedEvents() routine which is run periodically to re-send events the user has published to relays that haven't received them (i.e. because they were offline, the user was offline, etc.). I did some debugging and it seems like that function is not using the correct Core Data query to get all events that still need to be republished. IIRC `Event.unpublishedEvents(for: user, context: objectContext)` seems to be fetching events that don't actually need to be retried. Let's fix this so that we aren't doing unnecessary work and clogging up the logs.

**Comment by setch-l** [comment]
Hi @martindsq - This works but only for text and not for images. I tried to post a photo along with some text and only the text published when I came back online.
