### ISSUE TITLE
Wrong note opens when clicking on "replies" link

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos#275]
<img width="1136" alt="Screenshot 2023-04-27 at 16 58 09" src="https://user-images.githubusercontent.com/1935975/234903180-51abd8d0-e006-464e-9aab-364076da2281.png">

I don't know what is happening but when I click on "36 replies" in the top post then the clicking animation for the post below it plays and the thread for that post below it opens.

**Comment by setch-l** [comment]
@boreq - If you can reproduce this, please re-open the ticket. Given the age of the ticket I am going to close it.
