### ISSUE TITLE
Can't click on links from note card view

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#284]
![D6C27AC7-EE37-4641-8B07-1A1B385DA6C7_1_201_a](https://user-images.githubusercontent.com/76/235284477-15c0583d-c164-4077-897e-584ecd95e51e.jpeg)

On the note card view when you try and tap on a web link it shows that there's been a tap but doesn't open the link.

**Comment by mplorentz** [comment]
@rabble also reports that nothing above the bottom row of buttons on the note is tappable. Let's sit down and debug on his device.

**Comment by martindsq** [comment]
I can't either, I'll assign this to me

**Comment by mplorentz** [comment]
Confirmed by @rabble that he can't reproduce this anymore.
