### ISSUE TITLE
Add support for linking to and displaying notes shared with nostr:nevent and nostr:note links. 

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#285]
Nostr supports many different uri types including npub, note, naddr, nevent, nprofile, and naddress. We support npub and nprofile but not the others. This isn't much work, but it means we would be able to make links to content like in this screenshot work. We should support it both detected in the text of the links and also in the discovery search box. 

<img width="627" alt="Screenshot 2024-05-22 at 1 49 16 PM" src="https://github.com/planetary-social/nos/assets/76/f3075ea9-5960-4d0b-b5b8-139b250c461a">

**Comment by mplorentz** [comment]
@martindsq has added support for `nostr:npub` and `nostr:nprofile` in #281, but we should also add support for rendering `nostr:nevent` and `nostr:note` and support for searching for these values in the search bar on the discover tab.

**Comment by joshuatbrown** [comment]
@rabble I believe we've addressed this in #1231, #1232, and #1234. Feel free to reopen if I'm wrong about that.
