### ISSUE TITLE
[UI] Retracting reaction (like) - Delete message when we tap on the buttons again

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#286]
Nostr supports delete events, including for things like reposts and reactions. When we post something in Nos we should be able to tap the reaction button a second time to remove it. So if you accidentally repost something, you can retract it with a follow-up delete event. Same thing with reaction. This is a small feature but will make the app feel more natural and safer. 

![Screenshot 2023-04-30 at 9 29 11 AM](https://user-images.githubusercontent.com/76/235324985-b9140ee0-4293-46d3-88dd-4362982e1135.png)

**Comment by setch-l** [comment]
Note this only need to be be done for retracting a like. We already support retracting a repost.

**Comment by rabble** [comment]
Users are seeing this bug: https://damus.io/note1vjhdvfjwa8gexlfs3vzzc5su55kgkkx627zm9jsgln3hskq55dks5d9nvw

**Comment by setch-l** [comment]
I'm going to move the bug to a separate ticket - as these are two diff issues.
