### ISSUE TITLE
Can't access note options on the note view

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#287]
At the moment you can only access the three dot settings from the list view of posts but not from the card for a specific note. 

This is a regression bug i believe. It might be related to #284 which is another bug that you can't click on images or links within the note card. 

![Screenshot 2023-05-01 at 9 55 29 AM](https://user-images.githubusercontent.com/76/235377904-d9aa9b2f-48fa-4bb9-a2ee-0d8be4570498.png)
![ED611D6A-8AF3-4688-8938-49D387A5DB91_1_201_a](https://user-images.githubusercontent.com/76/235377937-f4bc7c9f-d766-4555-902f-b42bb32a245d.jpeg)

**Comment by mplorentz** [comment]
@mplorentz comment on this

**Comment by martindsq** [comment]
Couldn't reproduce this
