### ISSUE TITLE
Nos on MacOS never loads anything in explore

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#288]
In my install of Nos on MacOS, TestFlight Build 38, nothing ever loads in Discover, although content is getting added to working in the home feed. 

![Screenshot 2023-05-01 at 10 01 14 AM](https://user-images.githubusercontent.com/76/235378066-52bd875b-9b80-4b19-975c-28454dc73818.png)
[EE564FAE-9E72-4DA4-9E11-7697C58A33D6.zip](https://github.com/planetary-social/nos/files/11362484/EE564FAE-9E72-4DA4-9E11-7697C58A33D6.zip)

**Comment by mplorentz** [comment]
Probably related to high CPU usage - rabble said things do show up eventually

**Comment by mplorentz** [comment]
@rabble can you confirm this is still an issue?

**Comment by mplorentz** [comment]
Can't repro
