### ISSUE TITLE
UX - Tapping on bottom icons when in that tab, should take you back to the first screen of the tab

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#293]
In discover you can search for a profile, then see a post they've done, then see a person, look at their profile, and then see who they're following. Right now to get out, you've got to swipe right, over and over to make your way out. 

If you're in a tab, and tap that tab icon again, it should take you back to the beginning screen for that tab, scrolling you to the top. If you double tap on a tab then it should take you to the top and do a pull to refresh action.

**Comment by tony-capelli** [comment]
To make the user get out on when they press the tab view you can simply remove from the navigation stack all the views you have pushed by creating a NavigationPath():
`@State private var path = NavigationPath()`

 assigning it to the NavigationStack:

`NavigationStack(path: $path){ your view }`

 and then on the tabclick clear the navigationStack with path.removeLast(path.count)
