### ISSUE TITLE
Create a push notification service

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#302]
there is a notion doc for this

**Comment by boreq** [comment]
Let's close this long-living huge ticket in favor of those tickets:
- https://github.com/planetary-social/nos-notification-service/issues/5
- https://github.com/planetary-social/nos-notification-service/issues/6
- https://github.com/planetary-social/nos-notification-service/issues/7

Then we need to add the iOS tickets, for a start maybe those ones:
- [ ] send APNs tokens to the notification service
- [ ] correctly handle incoming notifications (e.g. open the correct view in the app when they are clicked, not sure how this works)
