### ISSUE TITLE
Add support for NIP-42 (AUTH)

### ISSUE THREAD

**Issue by pbennett** [planetary-social/nos#322]
Private relays will become more and more prevalent, so proper AUTH support is essential.
Pre-checking of NIP-11 info on the relay and the limitation object (note "auth_required") is probably advised since there's nothing that notifies a client that AUTH is required.  A relay may issue an AUTH challenge but the client may have already sent REQ's (for eg) that simply fail w/ a notice (that the client has no way of knowing what it corresponds to or if it's truly a failure).

**Comment by mplorentz** [comment]
Oops, I duped this with #1325, but I'm going to close this one. We're working on implementing this now!
