### ISSUE TITLE
Compare NIP-68, NIP-69, NIP-32, NIP-56

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos#333]
The goal of this is to figure out how to proceed with content reports and content warnings in Nos.

- https://github.com/nostr-protocol/nips/pull/532
- https://github.com/nostr-protocol/nips/pull/457
- https://github.com/nostr-protocol/nips/blob/master/56.md

**Comment by mplorentz** [comment]
We analyzed this and are moving forward trying to merge 32 and 68.
