### ISSUE TITLE
Add Confirmation Screen when users hit delete

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#346]
When users choose to delete content we need there to be a confirmation screen. Both to make sure they really want to delete things, but also explain that delete in a distributed system isn't assured and some relays might either ignore the delete all together or keep a copy even if they stop sharing the post. 

![105914B7-E88B-4D71-B25D-F75D5D5BEBAB_1_201_a](https://github.com/planetary-social/nos/assets/76/1e51e0a4-04ab-4058-ae76-5270917f1fcb)

**Comment by mplorentz** [comment]
The delete button should be in red too.
