### ISSUE TITLE
Send APNS token from iOS app to server

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#355]
We need to send the following data:
- apns token
- public key
- list of relays

**Comment by boreq** [comment]
Ok, this is happening now but needs to be implemented correctly by someone who knows iOS so that it actually handles errors correctly, asks user to show them notifications etc.

**Comment by boreq** [comment]
Just to write things down @mplorentz will be fixing the error handling in this pull request as far as I understand.

**Comment by boreq** [comment]
Unassigned myself because I am not actually the person doing this anymore.
