### ISSUE TITLE
Implement Fundraising Campaigns

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#384]

**Comment by Chardot** [comment]
Here's my design proposal for Fundraisers [(Link to Figma)
](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=2039%3A13342&mode=design&t=trcATWeyBTAVZZsB-1)
![Image](https://github.com/planetary-social/nos/assets/477835/2255bbf3-22a8-431d-bc2c-cdd7ebda4293)

**Comment by setch-l** [comment]
In an effort to clean up github I'm going to remove unplanned work. We have these designs and we can create tickets when we're ready to implement.
