### ISSUE TITLE
Profile: add number of followers and how I'm connected

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#391]

**Comment by Chardot** [comment]
Here's the design:

![Image](https://github.com/planetary-social/nos/assets/477835/2781c5d8-7eea-4519-bc99-7613b77081cb)

I'm proposing something very similar to Instagram, where they display the total number of connections in common and show up to 3 avatars of the closest (those who interact with you the most):

![Image](https://github.com/planetary-social/nos/assets/477835/e9c3e1a6-bf1b-42c6-a669-2aa321e9331e)

**Comment by mplorentz** [comment]
Consider fixing #455 when implementing this.
