### ISSUE TITLE
The empty home feed message overlaps pushed views

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#40]
Steps to reproduce:
1. Do a fresh installation of Nos
2. Open the side menu
3. tap "Your profile"
Expected: only the message about no events being shown for the profile is displayed.
Actual: The empty home feed message is also displayed.

![Image](https://user-images.githubusercontent.com/1165004/220773202-0fa314ce-84d6-45ea-8b74-b4308b01a88b.PNG)

**Comment by boreq** [comment]
Open issue in done.
