### ISSUE TITLE
Update Profile Design for SwiftUI Export

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#409]
As a SwiftUI dev, I want to see an updated profile screen design that is optimized to use the latest Figma SwiftUI export feature, so I can easily implement it.

**Comment by Chardot** [comment]
I updated the design adding the profile background image, but I haven't optimized the layers so it can be exported to SwiftUI yet.

![Image](https://github.com/planetary-social/nos/assets/477835/8a3daf7c-f8c1-4f45-8e58-1bb9a287a91d)

**Comment by Chardot** [comment]
I improved the spacing to accomodate more elements like the content tabs at the bottom of the profile card, and generated a new collapsed version for when the user scrolls down past the profile card.

![Image](https://github.com/planetary-social/nos/assets/477835/5061a2dd-3aab-4b04-80c6-42445e666b8e)

Check my [progress on Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=2093%3A15853&mode=design&t=j3PC7DVk5ev2JH2y-1).

**Comment by sathomp** [comment]
I like the addition of the collapsed version, it allows me to focus on what's below as I explore the page while still being able to take actions.
