### ISSUE TITLE
Replace Zendesk

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#443]
We want to get rid of Zendesk because it's expensive and it sends data to a third party. We need to replace what we were using it for:
- Support - we can use support@nos.social/support@planetary.social for this
- ToS, etc. - we can put these on our website or GitHub

**Comment by boreq** [comment]
I got stuck on this as the menu component in Planetary doesn't appear to be using swift ui. I think it is probably better to pick this up later when someone is available to help me out with this.

**Comment by mplorentz** [comment]
I'm back and available to help when you are ready @boreq.

**Comment by setch-l** [comment]
Created two new support tickets to move this to the website and Linda will monitor the support email.
