### ISSUE TITLE
[UI] Add action bar to reply screen

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#450]
We need the action bar that allows users to attach images and set an expiration date for the reply text box.

[Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=2412-18045&mode=design&t=pbkGVult8AYdZfXg-0)

**Comment by Chardot** [comment]
So basically we need to use the same view we designed for the message composer:

![Image](https://github.com/planetary-social/nos/assets/477835/9be28d0f-33e5-4dd2-82f6-9f852a0ff3f7)

Here's the [complete design in Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=1327%3A12016&mode=design&t=Io6S8ftNImXgfWd0-1)

**Comment by mplorentz** [comment]
@Chardot I feel like we're moving backwards here. It's a really nice feature to have the thread you are replying to in view when you are replying. That's how Messages, Twitter, Slack, Damus, etc. work. Can you explain why you prefer a fullscreen modal here?

**Comment by Chardot** [comment]
Here'sa a better proposal, reusing the note composer but including the note to which the user is replying at the top. What do you think?

![Image](https://github.com/planetary-social/nos/assets/477835/e983a66f-731d-4b58-b3ac-905217a50d40)

**Comment by mplorentz** [comment]
@Chardot that looks great! I'm curious how the scrolling should work. Is there any way to hide the message you are replying to? How it should look if the post you are replying to is very long?

**Comment by Chardot** [comment]
@mplorentz I think the sequence should be like this:

1. User taps on Reply
2. Composer UI slides in, containing the preceding note on top, and a prompt to write the reply below it.
3. After 500ms, the preceding note and reply prompt are scrolled up so that the first is out of view, leaving up to 3 lines of text into view as context for the reply.
4. User writes the reply.

If the preceding note is too long, its content will be truncated the same way we do on the Feed.

Here's a rendering of my explanation:

![Image](https://github.com/planetary-social/nos/assets/477835/71c87f80-15a1-44b5-b9aa-c6371052c140)

**Comment by Chardot** [comment]
@mplorentz It's pretty much the same thing Damus does, but we're leaving a portion of the preceding note to give better context for the reply, instead of hiding it completely:

https://github.com/planetary-social/nos/assets/477835/3b5c25cd-5e7c-4bc6-b864-a3ecde9f709e

**Comment by mplorentz** [comment]
@Chardot sounds good! I think we can move this to the top of the backlog!

**Comment by rabble** [comment]
@setch-l Do we really want to do this rewrite of the reply from? As you can see from the attached image, it doesn't work to just add the image upload and expiration actions. 

Personally i really like how nos lets me see posts in the thread when i'm writing a reply. I don't like the idea of losing that in the design that @Chardot has proposed. 


![](https://files.slack.com/files-pri/TDR0MCDJN-F06MMLPN96C/img_0421.png)

**Comment by mplorentz** [comment]
@rabble there was some discussion in Slack and I think you were looking at an old design, and your concern is addressed in the newer design. I started working on this to look for technical challenges so I'll just finish it out.

**Comment by setch-l** [comment]
@mplorentz - I realize that Josh created a new ticket to fix this, but I would prefer to simply hand this back to you with the following feedback:

1. Typing more than one line makes the entire screen jump
2. At three lines all the text is hidden so you can't see what you are writing.
