### ISSUE TITLE
Nos tells me to read more in my bio but there is nothing more to read

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos#455]
iphone se

https://0x46.net/me/nostr/

![IMG_0010](https://github.com/planetary-social/nos/assets/1935975/20db4258-1887-468e-b92a-5766edd558ef)

**Comment by mplorentz** [comment]
We should also make links tappable and text selectable in this box

**Comment by boreq** [comment]
> We should also make links tappable and text selectable in this box

- https://github.com/planetary-social/nos/issues/457

**Comment by rabble** [comment]
fixed
