### ISSUE TITLE
Fix high CPU usage in build 65

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#471]
@rabble and @Chardot are reporting high cpu usage in build 65.

**Comment by Chardot** [comment]
Using build 65 and we still experience this issue.

**Comment by rabble** [comment]
Seeems like this started in build 59

**Comment by mplorentz** [comment]
I haven't observed any instances of high CPU in the last few builds. I suspect it may have been related to a database cleanup bug fixed in #534. I'm going to close this and we can reopen if we see it again.
