### ISSUE TITLE
UNS add links / hooks for premiums names

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#480]
Add logic to the [nos.social](http://nos.social/) signup flow to direct users to the UNS web portal to get a premium name, and allow for users to signup when they already have a UNS name. Work with 
@Aleix López
 López to sort out the required API endpoints.

**Comment by Chardot** [comment]
Here's the design for that specific screen:

![Image](https://github.com/planetary-social/nos/assets/477835/04eb353c-3e52-4fed-807d-5732c737b323)
[[Link to Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=2644%3A8203&mode=design&t=UNQYYiV70A9txyRa-1)]

This is part of the UNS Registration Flow #434
