### ISSUE TITLE
Convert HomeView to use MessageCard from Planetary

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#5]
Let's copy over our MessageCard SwiftUI view from Planetary and modify it to display `kind: 1` Nostr events. Ignore colors for now because we don't have designs for those yet.

**Comment by mplorentz** [comment]
Jason will work on this.

**Comment by jcswift23** [comment]
https://github.com/planetary-social/nos/pull/17

**Comment by boreq** [comment]
Open issue in "done".
