### ISSUE TITLE
add support for crash reporting / tracking

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#509]
Look at using KSCrash because it's an open source / self hosted / no third party data system for ios. 

https://github.com/kstenerud/KSCrash

**Comment by mplorentz** [comment]
I'm going to give sentry.io crash reporting a try. The code is open source and self-hostable but not freely licensed. But in the event that sentry stop supporting self-hosting we can fall back on GlitchTip (an MIT option) which accepts events from the Sentry SDK. 

Sentry seems to have more active support and more users than most self-hostable options. They also appear to have robust performance monitoring tools which we need also. I also evaluated:
- KSCrash - doesn't include a web UI for viewing reports, and the web UIs they recommend are unmaintained
- Countly - is self-hostable but won't symbolicate crash reports unless you have an enterprise subscription
- Bugsnag - only has a "Request a Quote" option for self hosting, which is probably out of our price range.
- GlitchTip - looks fine but doesn't seem to have a lot of users
