### ISSUE TITLE
Add easy ability to copy user's nip-05 from their profile

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#564]
As a nos user looking aat a users profile, i want to be able to copy their nip-05 name when viewing their profile.

<img width="685" alt="Screenshot 2023-09-19 at 11 17 07 AM" src="https://github.com/planetary-social/nos/assets/76/16a73f3b-b275-4cf8-aa4a-9b3abb08eef0">

**Comment by Chardot** [comment]
Here's the design of the button to copy the nip-05.

![Image](https://github.com/planetary-social/nos/assets/477835/a94102b2-b3cd-410a-9828-2eddb49f7f17)

I'll attach the exported button in the next comment.

**Comment by boreq** [comment]
Open ticket in done.
