### ISSUE TITLE
Display better information when users puts a nip-05 in the search bar

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#565]
When you write a partial name on iOS it starts searching and displays matches. This doesn't happen in the mac version.

On both, if you put in a full nip-05 it should display something useful in the search results, ideally that specific users. Instead it waits for a enter event... tap on ios... and then takes you to a users profile. 

If folks don't know to hit enter, then the just think the search failed. 

Searching for a user name on mac:

<img width="685" alt="Screenshot 2023-09-19 at 11 22 47 AM" src="https://github.com/planetary-social/nos/assets/76/f6133326-0fde-4ed6-8b90-bbd7307fcc31">

Searching for the same text on iOS it works:

![IMG_E63ED9CFB0EA-1](https://github.com/planetary-social/nos/assets/76/27299eb2-fe57-441b-bdd7-18dd86e0725a)

Searching for the full nip-5 on mac and ios doesn't display anything, looks like it's broken until you hit enter and then it redirects.. Nobody will get this.

<img width="685" alt="Screenshot 2023-09-19 at 11 21 10 AM" src="https://github.com/planetary-social/nos/assets/76/58c8b5e9-dd71-451c-840a-fb537828a814">

**Comment by setch-l** [comment]
The layout for people search results has been updated. It appears there is a bug searching for external NIP05 IDs and displaying the results. Closing this ticket.
