### ISSUE TITLE
Mute list not being retained

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#566]
We've got a bug somewhere in the system. When our users mute content in Nos, it doesn't seem to stick. I've muted the screenshotted account, dozens of times. 

I thought it was that other nostr apps were blowing away the mute list when I muted somebody, but i've had it dissapear over the last couple of days and i haen't muted anybody on any app except Nos. 

I think we need to store a mute list locally. When we mute somebody new, we combine the mute list for our user that we can find elsewhere, with our local copy. Basically we shouldn't automatically reduce the size of the mute list. Instead when we find a mute list from relays for our account, we should ADD it to our locally held mute list. 

I have a suspicion that there are nostr apps which don't like muting at all, and are intentionally blowing away those lists. But i've got no evidence. 

<img width="685" alt="Screenshot 2023-09-19 at 12 17 51 PM" src="https://github.com/planetary-social/nos/assets/76/c4aa76e7-a9c1-4898-a9ad-afc41e744e8f">

**Comment by mplorentz** [comment]
Fixed in #586.
