### ISSUE TITLE
Fix out of memory crashes

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#574]
Rabble is seeing constant crashes on Nos on his Mac that make the app unusable. He opened Activity Monitor and saw that Nos was using 400GB of virtual memory. We need to figure out why the app is using so much memory and fix it.

**Comment by rabble** [comment]
Not just a mac thing, we're tracking it in sentry

**Comment by mplorentz** [comment]
A month or so ago I was doing some profiling in the app and noticed that some of our NSManagedObjectContexts were maintaining references to way too many events. I tried to figure out why but couldn't. Maybe this is related.

**Comment by mplorentz** [comment]
Rabble isn't seeing this anymore so we are pushing it back into the backlog.

**Comment by mplorentz** [comment]
Checking Sentry now we aren't seeing a lot of these. Closing.
