### ISSUE TITLE
Name search should look in the local database for authors not just on relays

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#581]
Often we know about users but somehow relays dont' show things. We should search the local db in addition to relays. 
![Screenshot 2023-09-30 at 10 52 15 AM](https://github.com/planetary-social/nos/assets/76/35201b77-fe5d-48f7-915f-028921e720c6)

**Comment by rabble** [comment]
This isn't a bug about looking locally,it's a bug where user profiles are incorrectly being deleted

**Comment by setch-l** [comment]
This appears to be working. I searched for multiple names and they all showed up in the list.
