### ISSUE TITLE
Require iOS 17

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#587]
This is a ticket to keep track of the subtasks we need to perform to make our minimum supported version iOS 17 when we eventually do.
- [ ] bump min version in Xcode settings
- [ ] Evaluate URL initializers (the [default initializer changed behavior](https://augmentedcode.io/2023/10/02/changes-to-url-string-parsing-in-ios-17/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B630) and there is a new `#URL` macro we can adopt)

**Comment by setch-l** [comment]
This work has been completed.
