### ISSUE TITLE
Show USBC account balance in profile

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#591]
As a user, I want to see my own USBC balance in my profile, so that I can be aware of how much USBC I've earned.

**Comment by Chardot** [comment]
I'm sharing a preview of my progress with this here.

On the left, the current Profile design and on the right, there's the new Profile design.

I think we can display a pill with the USBC balance. Right now I'm using an unrelated icon because I don't know what's USBC's symbol.

![Image](https://github.com/planetary-social/nos/assets/477835/51065056-f5b9-4c7f-a30c-2cb12c162474)

**Comment by Chardot** [comment]
@mplorentz Here's the design for this widget in both light and dark modes:

![Image](https://github.com/planetary-social/nos/assets/477835/e2b7549d-6ab6-45b5-a51f-16f9f2b04e73)

And a simple spec with the colors:

![Image](https://github.com/planetary-social/nos/assets/477835/fdc194b9-9106-4768-86d6-a04cbf7248f4)

The USBC logos for both themes are here:
[USBC Logo.zip](https://github.com/planetary-social/nos/files/13031378/USBC.Logo.zip)

**Comment by mplorentz** [comment]
Looks great! Moving this into the dev sprint.
