### ISSUE TITLE
I can't play a video by clicking on the play button

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos#628]
It only plays when I click outside of it.

https://github.com/planetary-social/nos/assets/1935975/a8d9ee54-ba8f-4870-b4ff-aa0bf4b53dae

**Comment by setch-l** [comment]
@boreq - I am not able to reproduce this on .99. 
1. In the feed I can click on a play button 
2. This opens the thread for the video and I click play again. 
3. This plays the video, but not the sound. 
4. If I click on the video again it goes full screen and I hear the sound. 

@Chardot - What is your expectation for how videos should render in the feed, threads etc.

**Comment by martindsq** [comment]
The videos play correctly for me, it does what Linda described. I suggest to close this for now and re-open the ticket in the future for a specific note that should play but doesn't.

**Comment by setch-l** [comment]
This is specific to the video type. Most videos render correctly in the app. For now we will close.
