### ISSUE TITLE
Android onboarding alternative, on website

### ISSUE THREAD

**Issue by VictorieeMan** [planetary-social/nos#635]
On the https://www.nos.social/ website it calls for joining a healthy social network, and then it says "get it on apple testflight". I bet there are visitors who don't own iPhones.

About this part of nostr being a healthy social network is the fact that different clients work cross the same protocol. On average people will assume that if they don't have the app they won't have access.

My recommendation is to primarily promote your app as you do, but also mention one or more android alternatives. Plus maybe explain how amazingly it is that different clients reach the same data.

Just a thought, about general onboarding to nostr! There's no reason to waste the lead on someone, just because they don't have an iPhone.

Best of luck :)

**Comment by mplorentz** [comment]
Good idea! CC @Chardot

**Comment by RasheedAZ** [comment]
I am confused. Is TeamOpen.Tech and Nos.social are about creating an iOS only app?

**Comment by rabble** [comment]
@RasheedAZ we’re building iOS first and will build android once we get the experience worked out on iOS.

**Comment by joshuatbrown** [comment]
@VictorieeMan thanks for the suggestion! We've done this now on our [install page](https://www.nos.social/install) so I think we can close this. Thank you so much!

**Comment by VictorieeMan** [comment]
Great! I think it's a good nostr eco-system move, to help new people find their way and realize that nostr itself is truly cross-platform :) Best of luck with the iOS app!
