### ISSUE TITLE
Fetch reports for replies

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#638]

**Comment by martindsq** [comment]
Reports for replies are being fetched from the relays, but reports for authors of those replies are not

**Comment by martindsq** [comment]
I moved the deletion task to a new ticket to give this more visibility https://github.com/planetary-social/nos/issues/728

**Comment by setch-l** [comment]
@martindsq - I cannot tell from the comments if you did work to fix this. If so what should I expect to see in the app when testing? Thanks!
