### ISSUE TITLE
Add search bar for looking up npubs

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#65]
Let's add a search bar to the discover tab that users can use to look up other users. It won't do full text search (yet), but it should accept npub format public keys and open the profile page for the user when "Enter" is tapped on the keyboard. The placeholder text should be "Find a user by ID". 

Note: right now we don't request any data from relays when showing the profile view, but that will be done in #66.

<img src="https://user-images.githubusercontent.com/1165004/222183352-e79a4137-4db1-4ba6-9a1c-7b0d8efefb1e.jpeg" width="300" />

**Comment by jcswift23** [comment]
Draft PR:
https://github.com/planetary-social/nos/pull/116/

The discover search bar works except for the extra vertical space.  Also, navigating to the profile view gets laggy if you paste in someone with a lot of posts.
