### ISSUE TITLE
Set up analytics for Stories

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#672]
As a Nos developer, I want to have analytics for Stories set up, so I can better understand how people use the feature in order to improve it.

Here are some analytics we want to set up

- [x] User enters stories view
- [x] User closes stories view
- [ ] Time spent watching a single story
- [ ] Time spent watching stories
- [x] User switches to next user
- [x] User taps to view note details
- [x] User likes a story
- [x] User reposts a story
- [x] User taps on user avatar to see profile

**Comment by martindsq** [comment]
Users cannot repost stories
