### ISSUE TITLE
Search results are not shown right away

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#681]
Steps to reproduce: 
1. Delete Nos
2. Reinstall
3. On the discover tab, search for a common name like "Matt"

Expected: Matts that you follow are shown instantly, then more Matts you don't know are streamed in from relays
Actual: Matts you follow may be shown instantly, but no more are shown until you hit "return" on the keyboard

I think our combine pipeline managing search results is not correctly refreshing the results whenever the managed object context is saved.

**Comment by rabble** [comment]
Using the app with a bunch of follows and existing data is worse than this experience.

Open discover tab.

Start typing.

Type "matt", only the 'm' appears, the app freezes, the cursor jumps to before the "m"...   I see a list of users who have an "M" in their name, then the cursor jumps to after the m after a couple of seconds, a "a" appears... the cursor again jumps to the beginning of the text box, it hangs for a bit, the cursor jumps back to after the "ma", then it flashes, the first "t" appears... It says "mat" then the cursor jumps back to the beginning, hangs, back to the end, then the last letter appears "matt"..... then nothing happens for some amount of time, sometimes a couple seconds, sometimes a minute... and then I see search results for Matt... 

Note, sometimes the order flashes around changing as it's displaying results.

**Comment by mplorentz** [comment]
I think there are several issues causing a poor experience here:
- In general we are downloading way too many events everywhere. This clogs up the parsing queue so your search results take a really long time to show up. This is a major problem with the app we are addressing in other tickets like #223 and #647.
- We probably shouldn't search for anything at all until you type at least 3 characters. This is pretty common as one or two letter queries will return too many results to be useful, so right now we are wasting network/battery/cpu downloading these events.
- It seems like the Combine pipeline doing the searches is somehow holding up the main thread, causing hangs. It may also not be cancelling previous requests properly when the query changes.

**Comment by setch-l** [comment]
@joshuatbrown - For this fix please also make the sure the following are true: 

Given that I am a user of nos.social 
When I type my 4th character in the search bar
Then I should start seeing results 
And when I type the 5th and subsequent characters, the previous queries should quit and only the new query should be running.

**Comment by joshuatbrown** [comment]
This is fixed in #867.
