### ISSUE TITLE
Fix reposts

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#689]
Many are rendering like this

![Image](https://github.com/planetary-social/nos/assets/1165004/2db0d4aa-55e6-420e-b273-4faa4d2d8746)

**Comment by mplorentz** [comment]
This is still an issue in the stories interface as of build 100.

**Comment by setch-l** [comment]
This appears to be fixed in build 101 and 128. I am no longer seeing it. Nice work!
