### ISSUE TITLE
Some notes show spinners and never load

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#703]
When browsing any feed sometimes a repost, linked note, or root note will fail to load and just show a spinner. We should make sure these always load if they are on a relay the current user uses.

I think this is caused by duplicate objects being created in the database which I wrote more about in https://github.com/planetary-social/nos/pull/696.

**Comment by setch-l** [comment]
This is still not fixed for posts by Charlie Stross on Build 112. 

[06799223-73DE-4924-B37A-7DE9F1EC1BAE.zip](https://github.com/planetary-social/nos/files/13704834/06799223-73DE-4924-B37A-7DE9F1EC1BAE.zip)



![Image](https://github.com/planetary-social/nos/assets/6765558/2d1a5cf8-f18c-49ab-bec1-530fec927f5a)

**Comment by mplorentz** [comment]
This is happening a lot on build 168. Reopening.

**Comment by mplorentz** [comment]
I've disabled the EventObservationTests for now. make sure to re-enable them before closing this ticket.

**Comment by mplorentz** [comment]
This is still happening. I did some more investigation but I'm pretty out of ideas on how to fix this. I still feel like the root issue is that duplicate Events and Authors are getting created in separate NSManagedObjectContexts (like the parseContext and viewContext) and then when they are merged the resulting data in sqlite is correct, but the SwiftUI views don't always get notified of the changes and update accordingly. So when we create a stubbed Event for a reposted note we haven't downloaded yet sometimes even after we have downloaded it SwiftUI doesn't display it.

One potential temporary hack would be to just have NoteCard refetch the Event from the database every few seconds. But this might cause performance problems and doesn't solve the real issue.

**Comment by mplorentz** [comment]
Maybe if we create Events and Authors using SwiftData we won't run into the deadlock? Something we could think about alongside #971.

**Comment by setch-l** [comment]
@mplorentz - I think this is primarily two scenarios: 
- the root note of a thread when you click in (see ticket #801 ) 
- reposts do not currently load in the app

For this ticket - let's focus on these two scenarios and if we have some remaining - we can create a new ticket for the next sprint.

**Comment by rabble** [comment]
Should we look at the solution of republishing notes to our relays when we republish a note. This means folks who find the repost event would be able to get the reposted event from that same relay.

**Comment by setch-l** [comment]
@mplorentz - It's not clear to me why issue 3 is happening. Is it because we are not republishing the repost and can't find it? Or is that a separate issue?

**Comment by mplorentz** [comment]
@setch-l that's a separate issue. We actually embed the reposted note inside the "repost" event when we publish them. But not every app does this, and it seems like we aren't properly handling events that don't.

**Comment by mplorentz** [comment]
It turns out that problem 3 doesn't have anything to do with the `content` field, and it doesn't impact our loading of notes. It's some kind of SwiftUI bug. As such it doesn't feel like it fits within this ticket and it feels much less important. I opened #1257 to track that issue specifically. CC @setch-l so you can set priority.

I also found another unrelated bug while working on this, which I wrote up in #1258.
