### ISSUE TITLE
reposted notes are not showing in stories interface

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#710]
Steps to reproduce:
1. Follow someone who has recently reposted something
2. Navigate to view their stories on the home tab
Expected: Their repost is displayed
Actual: no repost is displayed.

![Screenshot 2023-12-09 at 9 30 59 PM](https://github.com/planetary-social/nos/assets/76/e2796ccb-2c7b-4b13-8503-4a7bfbc5fcbe)

**Comment by setch-l** [comment]
This is working in build 128!
