### ISSUE TITLE
Native Paste option does not appear in Post when clicking on the post screen.

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#713]
Steps to reproduce:
1. Open your mobile device
2. Copy a link to a webpage 
3. Open Nos.social app 
4. Create a new post 
5. Tap to paste 
Issue: Nothing happens, the option to paste does not appear after tapping multiple times.

**Comment by mplorentz** [comment]
I think this is because the text view is not expanding to fill the space the user expects.

**Comment by joshuatbrown** [comment]
I think @mplorentz is right and that the text view does not fill the entire space. I'd like to fix that, and I'd also like to consider adding a paste button to the post screen. We could consider adding it to the bar that appears just above the keyboard, and this would give the user a much simpler way to paste.
