### ISSUE TITLE
String localization is not fully internationalized

### ISSUE THREAD

**Issue by tyiu** [planetary-social/nos#718]
Each locale has a different set of pluralization rules. The way that localization is [implemented currently](https://github.com/planetary-social/nos/blob/main/Nos/Assets/Localization/Localized.swift) assumes only English and English-like pluralization rules (one and many). For example, Arabic has 6 plural rules: zero, one, two, few, many, other.

I was wondering why localization was implemented custom in the way that it is, with the regex substitutions and all, when localization and full support of plural rules across locales is supported natively.

Xcode 15 [introduced](https://developer.apple.com/documentation/xcode/localizing-and-varying-text-with-a-string-catalog) string catalogs (.xcstrings) which seems to make it even easier than before to handle localization. Someone added [Crowdin support](https://store.crowdin.com/string_catalog) for .xcstrings files recently in the last few months.

**Comment by tyiu** [comment]
I started working on migrating over to string catalogs for fun at I was curious how it works. Also, I found a plugin that auto generates code from string catalogs, so type safety is retained. I'll share more once my branch becomes stable.

**Comment by setch-l** [comment]
@martindsq - Change the format of the translations in CrowdIn to the new one as outlined in this PR: https://github.com/planetary-social/nos/pull/738
