### ISSUE TITLE
Liking a post will make the feed position jump up

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#730]
Steps to Reproduce: 
1. Open nos.social after having it fully closed on your phone
2. Scroll down 
3. Like a post
Issue: the feed will jump back up after the like 

This appears to only happen on the first like after re-opening the app.

**Comment by mplorentz** [comment]
I think the home feed is updating its fetch request's date to `.now` in the view's init. This date should probably be kept as `@State` like the DiscoverView does. It's `date` variable looks like this:
```
@State private var date = Date(timeIntervalSince1970: Date.now.timeIntervalSince1970 + Double(Self.initialLoadTime))
```

There might be other feeds that are doing this too.

**Comment by setch-l** [comment]
closing as this is resolved
