### ISSUE TITLE
Move SwiftLint up in Build phases

### ISSUE THREAD

**Issue by vigotskij** [planetary-social/nos#734]
By moving SwiftLint processing before compiling the app we can catch any possible errors faster and without having to wait after all the process finishes.

This is a 2 minutes task 😄

**Comment by joshuatbrown** [comment]
@vigotskij oh wow -- this is awesome! I had no idea this would show warnings sooner, but I just tried it and you're absolutely right! Thanks so much for this and your other suggestions!

**Comment by joshuatbrown** [comment]
@vigotskij you were absolutely right -- a 2 minute task, and it's a big win for the developer experience. This is done now and in our `main` branch -- thanks again!
