### ISSUE TITLE
[NIP05] Display nos.social NIP05's in search result cards

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#748]
Given that I am a user of nos.social 
When I am viewing search result cards 
Then I should see the nos.social NIP05 for those users who have one.

**Comment by martindsq** [comment]
@setch-l @mplorentz I'm seeing the nip-05 in the search results cards. Mind checking if there is something I'm missing?

**Comment by mplorentz** [comment]
@mplorentz I see it to. I think this can be closed, but let's wait for @setch-l to weigh in.
