### ISSUE TITLE
Friendly user name flow

### ISSUE THREAD

**Issue by Chardot** [planetary-social/nos#749]
The current usage of npubs for account identification in nostr applications presents a significant usability challenge, especially for non-technical users. This is largely due to its deviation from the conventional user/password system ubiquitous across various platforms. To address this, a pivotal step involves the integration of [NIP 05](https://github.com/nostr-protocol/nips/blob/master/05.md) into the account creation process within the nos.app. By doing so, we enable user-friendly account identification, allowing users to select a name combined with our domain, such as daniel@nos.social.

[Read more in Notion](https://www.notion.so/nossocial/Nip-05-73daa999a74d470aa0f9c55c2f10e14f?pvs=4)

User story breakdown:

- [ ] As a new user of [nos.social](http://nos.social/) I want the ability to secure a friendly user name.
- [ ] As a user of [nos.social](http://nos.social/) I want to know if the name I’ve selected is already in use or not permitted.
- [ ] As an existing user of [nos.social](http://nos.social/) I want the ability to obtain a friendly user name.
- [ ] As an existing user of [nos.social](http://nos.social/) I want to know that the ability to claim a friendly user name is now available.
- [ ] As a user of [nos.social](http://nos.social/) when I have a NIP05 ID I want it to display on my profile in nos so users can easily know who I am.
- [ ] As a user of [nos.social](http://nos.social/) when I am reading a mention of a post by a NIP05 user where their NIP05 has been mentioned, I want to see the NIP05 name instead of the public key.
- [ ] As a user of [nos.social](http://nos.social/) I want the ability to change my NIP05 name.
- [ ] As a user of [nos.social](http://nos.social/) I want to be alerted to any implications of changing my NIP05 name.
- [ ] As a user of [nos.social](http://nos.social/) I want the ability to delete my NIP05 user name.
- [ ] As a user of [nos.social](http://nos.social/) I want to know the implications of deleting my NIP05 user name.

**Comment by martindsq** [comment]
@setch-l this issue should be closed as it is already done
