### ISSUE TITLE
Add tabs to Profile screen

### ISSUE THREAD

**Issue by martindsq** [planetary-social/nos#756]
As a user I should be able to show only the posts posted by the user I'm seeing in the Profile screen so that I can filter out content the user didn't created

**Comment by setch-l** [comment]
Per Sprint planning: 
Move the "Posts" tab to the left and rename to Notes. 
Move the "feed" tab to the right and rename to Activity.

**Comment by martindsq** [comment]
@setch-l this issue should be closed given that we already did this
