### ISSUE TITLE
Sometimes follow list would not be updated when changed from another client

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#760]
Steps to reproduce:
1. Sign into another client with your Nos profile
2. Follow someone
3. Unfollow someone else
4. Switch back to Nos and look at the list of who you are following
Expected: It shows the latest follow list including the changes you made in the other Nostr client
Actual: Nos does not process the changes.

**Comment by mplorentz** [comment]
This was a bug @tyiu noticed in his technical interview and he fixed it in #705. Thanks @tyiu!

**Comment by setch-l** [comment]
This works in build 128! Thank you @tyiu
