### ISSUE TITLE
[Bug] App crashes on a mac when liking a post

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#779]
Steps to reproduce

1. Open nos on a mac
2. Log out of one account
3. Log into another account
4. Search for a user in the Discover tab
5. Like a post on their profile

Issue: App crashes.

Log files and a sentry crash can be found in slack here: https://planetary-app.slack.com/archives/CM4EPK324/p1704384959209389

**Comment by joshuatbrown** [comment]
Tried to reproduce a few times; I wasn't able to.

**Comment by setch-l** [comment]
This appears to be fixed on build 0.1.5 (189)
