### ISSUE TITLE
[NIP05 Edit Profile] Viewing the edit profile screen when i have another provider’s NIP05

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#815]
Given that I am a user of nos.social and I have a NIP05 from another service
When I view my profile screen
Then I should see the NIP05 associated with my NPUB in the username field 
AND 
I should NOT be able to edit or delete it. 
AND I should see the following text below. 

Please visit [domain name] to update your username.

**Comment by martindsq** [comment]
@Chardot
