### ISSUE TITLE
Profile photos and names fail to load in stories

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#818]
Steps to reproduce:
1. Install a fresh copy of Nos
2. Log into an existing account that follows a good number of people
Expected: the stories section at the top of the home feed loads profile pictures eventually
Actual: The profile photos never load. Even if you tap into a story and start reading them the profile photos don't show up.

<img src="https://github.com/planetary-social/nos/assets/1165004/f4239954-e87b-4c80-8396-2a70fe478f04" width="300" />

I think there are two technical problems here: the stories views aren't requesting profile metadata from relays when they are displayed, and they aren't properly observing changes to the Author models.

**Comment by setch-l** [comment]
This bug has been resolved by other fixes and is no longer an issue in the app.
