### ISSUE TITLE
Fix double navigation bar

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#83]
Right now the main tabs are nested inside two navigation bars: the one in AppView, and the one in their own view (HomeFeedView, DiscoverView, etc.). Let's fix this because it prevents the main tabs from adding items to the outer navigation bar. I'm not sure what the best way to restructure things is. Maybe when an item is tapped in the side menu we can just present it modally for now.

**Comment by jcswift23** [comment]
As part of this ticket, fix the vertical space issue in the Discover search bar from this PR:

https://github.com/planetary-social/nos/pull/116
