### ISSUE TITLE
Date takes most of the horizontal space in the Notification screen

### ISSUE THREAD

**Issue by martindsq** [planetary-social/nos#831]
![IMG_D969E76E3F52-1](https://github.com/planetary-social/nos/assets/1703242/754b3ef9-f268-40d8-84c7-61d58bca2075)

**Comment by joshuatbrown** [comment]
@martindsq Is the solution as simple as using a DateFormatter with the [dateStyle](https://developer.apple.com/documentation/foundation/dateformatter/1415411-datestyle) set to `.short` or `.medium`? I'm assuming from the screen shot that we're using `.long`.

**Comment by setch-l** [comment]
@joshuatbrown @martindsq - This is the design I found in figma for Notifications. Could we just use days and weeks (not necessarily the rest of the design - only the grey part) so for example 1d , 5d, 2wk, 4wk next to each post?

**Comment by martindsq** [comment]
We already have code that shows 1d, 5d,2wk, etc in the expiring posts (or elsewhere) so I think that's an easy solution. Or just use short or medium format as Josh suggests. Both are easy to implement.

**Comment by setch-l** [comment]
Let's follow Sebastian's approach of 1d, 5d, 2wk etc. I'll pull this into the dev backlog.

**Comment by setch-l** [comment]
This is fixed and working in the current build
