### ISSUE TITLE
[Design] Create threads prototype for new proposed experience

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#841]
Our current threading UI makes it hard to understand the different branches and replies. Sebastian has a proposal for a new option that we can test with users. This ticket is to create the prototype for the user test. 

Please reference the user research plan interview questions when creating the prototype: https://www.notion.so/nossocial/Threads-Prototype-Test-9a40aa5657ea444fadd6c2df1f3da0ac

**Comment by Chardot** [comment]
[This is the current state of the prototype](https://www.figma.com/proto/s0qf4VmyQygydP8MIQazZc/Nos?page-id=4219%3A6581&type=design&node-id=4328-1261&viewport=-30%2C297%2C0.22&t=b5cEkDC8UbRnzTdP-1&scaling=min-zoom&starting-point-node-id=4326%3A763&show-proto-sidebar=1&mode=design), using empty cards to demonstrate the browsing interaction. I'll recreate an actual thread with real content in the next iteration.

[Try the prototype](https://www.figma.com/proto/s0qf4VmyQygydP8MIQazZc/Nos?page-id=4219%3A6581&type=design&node-id=4328-1261&viewport=-30%2C297%2C0.22&t=b5cEkDC8UbRnzTdP-1&scaling=min-zoom&starting-point-node-id=4326%3A763&show-proto-sidebar=1&mode=design) from your phone, and swipe to browse the different replies to the original note.
