### ISSUE TITLE
Crash when tapping Manage your Universal Name

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#851]
Steps to Reproduce:
1. Launch a fresh install of Nos on the Mac
2. Create a new key in onboarding
3. Tap the profile tab
4. Tap the ellipsis button in the top right
5. Tap "Edit Profile"
6. Tap "Manage your Universal Name"
Expected: UNS wizard opens
Actual: App crashes.

[Sentry crash data](https://sentry.nos.social/organizations/verse/issues/827/?query=is%3Aunresolved+No+Observable+object+of+type+CurrentUser+found&referrer=issue-stream&statsPeriod=14d&stream_index=0)

**Comment by martindsq** [comment]
Just happens in Mac for me

**Comment by mplorentz** [comment]
Closing since we are removing UNS integration from the app.
