### ISSUE TITLE
Report user menu on iPad isn’t accessible / visible

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#868]
On an iPad, when I go to report a user, it puts the report menu tiny and at the bottom of the screen. You can’t see the options.

Uploading RPReplay_Final1706869311.mp4…

**Comment by urvi-k** [comment]
Hello @rabble, I would like to work on this issue if you agree.

**Comment by setch-l** [comment]
Hi @urvi-k - We'd love to have you help us with this ticket. Please feel free to pick up this work and submit a PR. Our CTO @mplorentz will review the PR when it's submitted. Thanks again!

**Comment by setch-l** [comment]
@joshuatbrown - Did you fix this? or @urvi-k Did you fix this? I'm noticing it's fixed on staging?

**Comment by joshuatbrown** [comment]
@setch-l @mplorentz OK, so I tracked down what's going on here. We're not able to display that confirmation dialog from the three-dots button. We have to choose a different view. One of the simpler choices would be to display it from the ProfileHeader so it would appear like this:

![Image](https://github.com/planetary-social/nos/assets/59564/d2eb1635-cec2-4617-b30a-d76f72f1f1f2)

I'd say this isn't ideal, but it's certainly a solution that gives the user the ability to report a user on iPad. I'd vote we go with this for now and redesign in the future.

**Comment by joshuatbrown** [comment]
Realized a video would be better to demonstrate the flow:

https://github.com/planetary-social/nos/assets/59564/146e73d5-95af-4863-9e67-4c9e54660d60

**Comment by joshuatbrown** [comment]
@setch-l @mplorentz I just retried and we _can_ actually show the menu from the ellipsis button, so I'll do that, and everything will just work as expected. I'm not sure why I had trouble with that before, but it's working for me now on both device and simulator.
