### ISSUE TITLE
[Bug] Following and unfollowing an npub we don't have data for causes an error

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#869]
Steps to reproduce:

1. open the latest build of nos
2. navigate to the Discover tab
3. Enter this Npub into the search bar: npub1f4faufazfl4cf43c893wx5ppnlqfu4evy2shc4p9gknfe56mqelsc5f7ql
4. You are automatically taken to the profile page.
5. Follow the user

Issue: It says error where the npubid was and it does not look like I was able to follow the user.

![Image](https://github.com/planetary-social/nos/assets/6765558/d5443190-2fc7-425e-b574-b6af21a66a31)

**Comment by joshuatbrown** [comment]
This seems to be fixed in #867, so let's test it after that merges and gets into a build.
