### ISSUE TITLE
Liking one note, auto populates additional likes additional notes as you scroll and the wrong link images 

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#873]
Steps to reproduce 
1. Open the nos fee
2. Scroll down 
3. Like a note
4. Keep scrolling
Issue: additional notes will be liked 

See this post: https://damus.io/note1vjhdvfjwa8gexlfs3vzzc5su55kgkkx627zm9jsgln3hskq55dks5d9nvw

Also see this thread in slack: https://planetary-app.slack.com/archives/CM4EPK324/p1706644375174589

See this slack post for the link images loading incorrectly: https://planetary-app.slack.com/archives/CM4EPK324/p1707442698601269

**Comment by rabble** [comment]
Do we know if it’s actually liking those other notes or just showing the other notes as liked. Is this a display issue or an issue if creating extra reaction events.

**Comment by mplorentz** [comment]
This looks like another instance of this bug: https://planetary-app.slack.com/archives/CM4EPK324/p1710270420095749
