### ISSUE TITLE
Hide links / urls to media on the discover screen cards

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#876]
When viewing note cards on the discover screen, we should NOT display urls or links. It looks ugly and nobody would want to tap on a link with these cards anyway, you’ll want to tap through to the full card. 

![IMG_0007](https://github.com/planetary-social/nos/assets/76/74e5da9e-39e4-475d-a278-1ddc2adead64)

**Comment by setch-l** [comment]
We are going to get rid of content on the Discover tab in the near future. I'm not sure we need to fix this before we transition discover to discovering people.

**Comment by joshuatbrown** [comment]
Closing since the Discover tab has changed completely.
