### ISSUE TITLE
Update sorting of discover cards so they’re not clumpy with repeats of posts from the same person

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#877]
Right now our discover tab sorts notes based on database id, basically when it was processed from the relays. This means that we tend to get a bunch of notes from one user, then another, then another. When you look at it on the discover tab, you’re going to get all the posts from one user, then then the next, etc… 

We need to solve the issue of why we see so few notes in discover, but we also need to sort them better. As long as we’re only showing less than a couple hundred notes, we should just sort randomly… obliviously we could do some ML algorithm but random would be better what we have. 

![IMG_0009](https://github.com/planetary-social/nos/assets/76/493c2151-c185-47f2-8ce1-fc45fd253df0)

**Comment by setch-l** [comment]
We are going to redo the discover tab to feature accounts rather than content in the near future. We don't need a ticket to fix something we're not going to keep around.

**Comment by joshuatbrown** [comment]
Closing, as the Discover tab has been completely reworked.
