### ISSUE TITLE
Remove unnecessary “read more” button from short notes

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#880]
For some reason we’re showing a read more button on very short notes and when you tap on it the read more button disappears. 

https://github.com/planetary-social/nos/assets/76/1066aebd-ca1a-4eca-a6fa-9b20ae12440f

**Comment by rishatl** [comment]
Hey, I'll take it upon myself, make me assignees, pls

**Comment by joshuatbrown** [comment]
@rishatl have you made any progress on this before I get started?

**Comment by mplorentz** [comment]
I think this might be because `instrinsicSize` is being calculated using `noteText` instead of `formattedText` in `CompactNoteView`.

**Comment by mplorentz** [comment]
Oops I fixed this while working on #450. I will submit a PR.
