### ISSUE TITLE
[bug] Search stops showing profile cards when the fourth letter is typed

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#888]
Note the following video contains two different examples. 

In the first example, the search works fine with Leurico8 bc I added him as a follower and have been messaging with him. You can see the card remains. 

However if I search for someone else like Lordes - the cards appear very briefly and then disappear and there is no option for similar results. 

I would expect if some results show up, that those remain until the background search concludes.

**Comment by setch-l** [comment]
https://github.com/planetary-social/nos/assets/6765558/6e58a202-7622-407f-803e-7a0dcde44c39

**Comment by joshuatbrown** [comment]
@setch-l I think what we're seeing here is that there are matches for the term "Lor", like corndalorian and Taylor Lorenz, and there are matches for "Lord", like Karo Zagorus (btcdragonlord@btcfur.com) and LordWoolamaloo. But there are no search results for "Lorde", so we don't display anything, and the same is true for "Lordes". 

We do continue to show results while the search is in progress (loading), as long as the search term matches the results. So for example, you could type "Lor" and see Taylor Lorenz, then add an "e" so the search term is "Lore" and Taylor Lorenz should still appear, as we continue looking for more results that match "Lore". I'm pretty sure that's how it _should_ work but I don't know that it _does_ work that way. I think there's a bug in that, actually.
