### ISSUE TITLE
[website] Add info about Android to Install page

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#897]
Acceptance criteria 

- Below the iOS images and above step 1, add the following line of text. 
Nos is presently iOS only. For access on Android we recommend [Amethyst](https://play.google.com/store/apps/details?id=com.vitorpamplona.amethyst&hl=en_US&gl=US).

**Comment by Chardot** [comment]
I added the section for Android users, made it [Android green](https://developer.android.com/distribute/marketing-tools/brand-guidelines#android_robot) which is easy to recognize for Android users, and here's how it looks:

On mobile:

![Image](https://github.com/planetary-social/nos/assets/477835/eb6e495e-056a-4d1f-99be-b7605da49b80)

and on desktop:

![Image](https://github.com/planetary-social/nos/assets/477835/f4d6525b-19f0-40d1-8cbb-b79e6a1a2ec9)

**Comment by setch-l** [comment]
Hi @Chardot - Perhaps it is there in the live site, but Amethyst is missing the underline for a hyperlink in the body text. We should definitely link out to the Google play store for them - they do not appear to have a stand-alone website.

**Comment by Chardot** [comment]
> Hi @Chardot - Perhaps it is there in the live site, but Amethyst is missing the underline for a hyperlink in the body text. We should definitely link out to the Google play store for them - they do not appear to have a stand-alone website.

Hi @setch-l! I added the underline for consistency with other links in the site. The URL is linking to their Play Store page. I'm deploying it to the live site.
