### ISSUE TITLE
Build a skeleton onboarding flow

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#9]
We are going to have a few onboarding screens that we show to new users, much like we do in Planetary. (you can simulate onboarding in Planetary by going to side menu -> Settings -> Advanced -> Debug menu -> Logout and Onboard). We don't know exactly what the content will be, but we can go ahead and write the logic to: 
- detect if this is the app's first launch (if there is no private key in storage)
- generate a new private key, or support the user pasting one in
- show a series of screens that the user can click next to navigate through
- Dismiss and show the home view at the end.

**Comment by mplorentz** [comment]
Shane will work on this

**Comment by boreq** [comment]
Open issue in "done".
