### ISSUE TITLE
[Experiment] Exclude relays that Relayable uses from our Read list

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#903]
The Nos app is receiving lots of duplicate events from across the network. 

For this experiment exclude reading from Relays that Relayable reads from to see if any of the following improve:
- reduction in bandwidth usage of the app on cellular networks
- elimination of duplicate posts in the home feed (note this is happening on multiple clients across the network) 
- improved performance - less crashes, faster loading etc. (have Rabble test for this)

**Comment by joshuatbrown** [comment]
Based on https://relayable.org, these seem to be the relays to exclude from our reading list if Relayable is one of the user's relays:

- relay.damus.io
- purplepag.es
- relay.snort.social
- nostr.wine
- nos.lol
- nostr21.com
- relay.wellorder.net
- nostr.mom

**Comment by joshuatbrown** [comment]
@martindsq makes a good point in this comment on the Draft PR: https://github.com/planetary-social/nos/pull/927#issuecomment-1981260133

If we were to go this route, we'd be fairly dependent on Relayable even though the user may have some of these other relays in their list. I'm not sure if that should stop our experiment or not. @setch-l?

**Comment by joshuatbrown** [comment]
I just realized we also have a conflicting experiment going on right now where some of us are trying out just three relays to see how that works.
