### ISSUE TITLE
[Experiment] Relay Proxy

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#906]
Staff can run the following experiments. Each experiment will take 1 hour. 

Both experiments should be conducted using build 199 

Experiment set-up 
Turn off the wifi on your device 
Reset the cellular bandwidth usage on your phone. 
Open the nos.social app and use it continuously for 30 min
Take a screen shot of the bandwidth used 
Take a screen shot of the Energy use by the app 
Note any performance issues, crashes etc you encountered during those 30 min. 

Next, remove all relays on your device except for either primal cache: cache2.primal.net/v1
or relayable. 
Delete the app from your phone 
Reset your cellular bandwidth data 
Reinstall nos.social 
Reconnect your nsec 
Play with the app for another 30 min or so 
(In Rabble's case, leave the app in this state overnight and continue using the app in the morning) 
At the end of 30 min: 
- take a screenshot of bandwidth use
- take a screenshot of energy use 
- note any improvements in performance. 

Use the comments below to upload the data for your experiment.

**Comment by dcadenas** [comment]
### Control group with 9 relays
<details>
<summary>
This is the result of my first control group of 30 minutes in which I had the default 9 relays:
</summary>

![Image](https://github.com/planetary-social/nos/assets/18184/b964690e-2597-4d1c-985f-8d91077b6258)
![Image](https://github.com/planetary-social/nos/assets/18184/3298e026-7155-40b6-84aa-e98332afc579)
https://github.com/planetary-social/nos/assets/18184/53b034b3-e5bb-434a-a77b-900521fe1985
https://github.com/planetary-social/nos/assets/18184/5355afd2-9486-461f-bfa9-64ec183ce827

</details>
Notes: Scrolling felt sluggish and I could notice the phone getting hot. I had a single crash in the discovery tab. Didn't notice many loading animations.Also noticed a bigger number in the relay counter than those I was using.


### Experiment
<details>
<summary>
Here are the results of using only relayable.org:
</summary>

![Image](https://github.com/planetary-social/nos/assets/18184/0e797381-43b3-4c28-9dca-f3c19ff154a7)
![Image](https://github.com/planetary-social/nos/assets/18184/3ebb0f41-9604-4f17-b8a1-54caaa1f5ce2)
https://github.com/planetary-social/nos/assets/18184/d6ff1b7c-1da8-4cdb-a1fd-fda8096d5909

</details>
Notes: Scolling felt better now but still geting the phone hot. No crashes but saw a lot of loading indicators that after a while would get solved. It felt like relayable was refusing to respond so I was asumming it was some rate-limiting?
