### ISSUE TITLE
Reply text area doesn’t scroll with text on longer replies 

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#931]
When writing a reply that’s more than a dozen lines long the text doesn’t scroll to stay visible above the keyboard. Instead the text is hidden behind the keyboard so it is hard to see or edit what you’re writing.  

See video: 

https://github.com/planetary-social/nos/assets/76/20578e09-c927-469c-a247-b0ebe20a4755

**Comment by setch-l** [comment]
This is fixed
