### ISSUE TITLE
[Posting] Allow users to upload video files in posts

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#934]
Given that I am a user of nos
When I select a media icon while creating a post
THen I should be able to upload videos as well. 

Videos should appear in the Apple pick list dialogue.

**Comment by setch-l** [comment]
@mplorentz - Not sure if this has made it to staging build 236 but i cannot upload photos in a normal post on that build on staging.

**Comment by mplorentz** [comment]
@setch-l this feature work actually hasn't hit TestFlight yet. I think we should file a separate bug ticket to look at photo uploading because the issue must be from code unrelated to this work.
