### ISSUE TITLE
[Dark Theme Updates] Update hex colors across the app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#938]
Hex colors should be updated to the following: 

Primary #FFFFFF
Secondary #A588D8

**Card background gradients** 

Card_bg_top, #2B1C47

Card_bg_bottom, #25183D

Design Reference files: 
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169%3A25565&mode=design&t=LBpUiD56mtD2Jjot-1

Background color reference files: 
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A32180&mode=design&t=LBpUiD56mtD2Jjot-1

**Comment by joshuatbrown** [comment]
@setch-l @Chardot just want to confirm I have the right scope for this. I'm seeing only Card_bg_top and Card_bg_bottom listed here in the GitHub ticket as well as in Figma. I've updated both of those. However, we have lots of other similar colors in the app, so I wonder if those also need to be updated as part of this ticket. Or will we update them in a separate ticket later? Here's a screenshot of similar colors and their names from the app:

![Image](https://github.com/planetary-social/nos/assets/59564/1d69a365-36c1-4eeb-a6e5-d91406656a32)

**Comment by Chardot** [comment]
> However, we have lots of other similar colors in the app, so I wonder if those also need to be updated as part of this ticket.

@joshuatbrown The scope of this ticket is to update the card background and secondary text colors. The rest of colors on this list should be updated in a future ticket because they apply to components in the app which I have not updated yet.
