### ISSUE TITLE
Wire up Report a Bug button (more logs)

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#94]
For now it can just open an email compose view controller for support@planetary.social and attach the current app logs.

**Comment by jcswift23** [comment]
I found this code that may be able to do it:
https://stackoverflow.com/questions/56784722/swiftui-send-email

**Comment by jcswift23** [comment]
Matt recently added the Logger library which has a function for getting the log file URLs I think, and planetary has some code for zipping them up as well. We can add that in a future PR.

The logs might be kind of sparse for now. At some point we need to go through and change all our print statements to Log.info() or similar.
