### ISSUE TITLE
[NIP05] Add list of relays when creating nip05 entry

### ISSUE THREAD

**Issue by dcadenas** [planetary-social/nos#964]
NIP 05 lets us define a list of relays next to the name associated with the pubkey. Our API does this through the relays parameter that may be passed through the [POST payload](https://github.com/planetary-social/nip05api?tab=readme-ov-file#post-payload-structure). By default we always add wss:://relay.nos.social but it wouldn't hurt to add the relays selected by the user.

**Comment by dcadenas** [comment]
This will involve only iOS app changes, the API is ready to receive these relays so I'm adding @martindsq just so it gets into the iOS team.

**Comment by setch-l** [comment]
@martindsq - Follow-up I changed my relays on tester12@nos.social account to 6 relays. I deleted and reinstalled the app and also logged into Primal with this account. 

relay.nos.social was not added to my list. Is that what I should expect to happen?

**Comment by setch-l** [comment]
@martindsq - Works great - thanks for the info to test!
