### ISSUE TITLE
[Profiles Update] Update NIP05 display on Profiles to accommodate long handles

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#966]
Problem 
- Some users have extremely long handles which are wrapping in a hard to read manner on mobile devices. 
- Example: npub147ra0fhs4aqvxz734dfs2kasryn63fsl9an8yjcyppaqmrry5q8sr5p0ws

Acceptance Criteria 
- Update NIP05 display on the top of the profile so it can accommodate very long handles / NIP05s

**Comment by Chardot** [comment]
[This is my progress with the Profile UI](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5513%3A6882&mode=design&t=NMMzw1IGTRXmU9u6-1) for long usernames. I got feedback from Linda and am working on improving the proposal.

**Comment by Chardot** [comment]
[This is the improved design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5513%3A6882&mode=design&t=LEwnScaccos6Ue4T-1) for displaying long display names, user names (NIP-05) and bios.

![Image](https://github.com/planetary-social/nos/assets/477835/6231450d-07ff-45ab-b1f8-8ac518481b99)

### The problem:

The current layout breaks with long display names and user names:

![Image](https://github.com/planetary-social/nos/assets/477835/fdab57ad-eb7a-4eff-aa3a-2c4c9877bf60)


### Solution:

Keep long display names in one line and trim them at the end.
Split the nip-05 into
- user
- instance/server
- network/bridge

![Image](https://github.com/planetary-social/nos/assets/477835/043756de-83d9-4f61-bc6f-c8cff03a8c40)

Tapping on display name, user name and/or bio will open the current Bio sheet with all this information in detail.

![Image](https://github.com/planetary-social/nos/assets/477835/13a958c2-2f32-449e-a8cd-22420454bdcc)

### Followers

Followers count has been removed and its place is taken by the Follow/Unfollow button.

Tapping on any part of the "Followers in common" block will open the Followers list:

![Image](https://github.com/planetary-social/nos/assets/477835/b32db073-1b1a-4579-b8bb-2efc7b054cbc)

Let me know if you need me to expose any other details on [this design on Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5513%3A6882&mode=design&t=LEwnScaccos6Ue4T-1).
