### ISSUE TITLE
[Bug] Fix color regressions on Profile page

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#967]
Recent changes to the profile screen changed the colors of the 3 dots menu in the upper right and the followed by have both turned orange/red. They should both be white. 

![Image](https://github.com/planetary-social/nos/assets/6765558/136dbd0f-362d-46a5-9e4a-7a393753e23c)

AC 
- 3 dots menu and followed by text should be white.

**Comment by mplorentz** [comment]
Maybe the app's tintColor was changed? I'm also seeing the orange on the activity wheel shown when a note card is loading (like a root note or repost).
