### ISSUE TITLE
Tapping the Notifications tab sometimes causes the app to hang

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#970]
Sometimes when I tap the Notifications tab, the app just hangs. I've seen this in the debugger before, and I _think_ it may be related to multiple managed object contexts trying to save at the same time. But I could be wrong.

Steps to reproduce:

1. Launch the app
2. While the Feed or Discover tab is still loading, tap the Notifications tab
3. If you're (un)lucky, the app will freeze up
4. If you're super lucky, you'll be in debug mode and be able to see what's happening

**Comment by joshuatbrown** [comment]
Just happened to me again, but I don't have any better steps to reproduce. This happened after I logged out of a throwaway test account and logged into my personal one. It's hung on the Notifications tab with a bunch of missing data:

![Image](https://github.com/planetary-social/nos/assets/59564/9a99ffde-548b-4f7d-8424-dd88a6b1a3a5)

**Comment by joshuatbrown** [comment]
I just had the app hang again. This time it's in my open PR where I added code that uses `persistenceController.saveAll()`. Here's the commit and the line that's hanging (again, based on pausing in the debugger, continuing, pausing again, and seeing the same line): https://github.com/planetary-social/nos/pull/1100/commits/5ee3b94d231c2e0d04314fd4757108f9c70f06e1#diff-437396bafa74ddc6f1556cd6b30eff884465099690729e1c8e685ada4602cf1cR148

<img width="1819" alt="Screenshot 2024-04-30 at 3 52 25 PM" src="https://github.com/planetary-social/nos/assets/59564/ee846713-d238-4924-af55-e5e7dee5312e">

I think there's a problem in one of the following:

1. `PersistenceController.saveAll()`
2. `NSManagedObjectContext.saveIfNeeded()`, which is called by `PersistenceController.saveAll()`

**Comment by mplorentz** [comment]
This looks similar to the deadlock I experienced when working on https://github.com/planetary-social/nos/pull/696. I never figured out what was wrong but I think it had to do with NSManagedObjectContexts trying to lock things so they could do a save, and two of them trying to lock on the same thread. Maybe that's not what's going on here but it's a place to look.
