### ISSUE TITLE
[Bug] Can't see text beyond the first three lines in Post or Reply

### ISSUE THREAD

**Issue by joshuatbrown** [planetary-social/nos#975]
1. Type a lot of text into a Reply or Post.
2. Observe that you can't see anything past the third line.

**Comment by rabble** [comment]
Here’s a video of it happening 

https://github.com/planetary-social/nos/assets/76/bcbe7133-740b-4141-9c9c-409fb05a2254

**Comment by rabble** [comment]
This is still happening in build 228.

**Comment by setch-l** [comment]
We used a diff process to address this bug AND it's fixed now!
