### ISSUE TITLE
[Bug] App is attributing content from one account to another account

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#977]
On Friday I was scrolling through build 222 and I noticed that PablO7z was posting release notes for the latest Nos build. I went to their profile and noticed a bunch of previous release notes and the delete post from a few weeks ago. I continued to flip back and forth - in part bc I thought I had mis-remembered Martin's display name. Eventually all of that content went away and PablO7z’s real content started populating.
Steps to reproduce:
Log out of the app
Delete the app
Re-install
Re-enter the same key used before logging out
Issue: The content appearing for profiles seems to not line up with the correct profile.
I think this is a critical bug. I can see if I can reproduce today.

See slack message for additional confirmation of the issue: https://planetary-app.slack.com/archives/CM4EPK324/p1711375783638379

**Comment by joshuatbrown** [comment]
The PABLOF7z account shows up when searching for the Nos.social account by public key. Steps:

1. Copy the Nos.social public key: `npub1pu3vqm4vzqpxsnhuc684dp2qaq6z69sf65yte4p39spcucv5lzmqswtfch`
2. Tap the Discover tab
3. Paste the public key into the search bar
4. Observe PABLOF7z profile

![simulator_screenshot_F9EFD2D8-7150-47B9-BB6C-552127629030](https://github.com/planetary-social/nos/assets/59564/ff800729-a0a6-47e6-b952-c8fcf56606a8)

**Comment by joshuatbrown** [comment]
@rabble [reports](https://planetary-app.slack.com/archives/C04PLR5QFQQ/p1711604241811069) that this has been fixed.

**Comment by mplorentz** [comment]
I didn't see the event in question but it looks good now on my machine. Moving to UAT.
