### ISSUE TITLE
[Notifications] Design a notification for a follow

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#979]
We want to notify users that someone new has followed them. 

In the notification the user should see the following:
- Profile pic 
- Display name / NIP05 of the person who followed them
- Ability to click in to view the profile of the person who followed them

**Comment by rabble** [comment]
This is good, but also remember that finding a new follow is actually way trickier in Nostr than you’d think. We’ll need functionality in the event service that looks at contact lists for users and notices a change. Then that new follow can be pushed to the notification service which sends the data to the user. Anyway, the UI part is easy for this functionality unfortunately.

**Comment by Chardot** [comment]
[Here's the updated design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5791%3A22590&mode=design&t=NW5ueLLPC0mGzk55-1) for Follow notifications.

I'm introducing a smaller version of the follow/following button to make room for really long display names. Also I'm proposing to move the timestamp to the end of the notification text string for the same reason.

![Image](https://github.com/planetary-social/nos/assets/477835/ab8b2b65-5e16-4ca8-92c3-837a7c1617e3)
