### ISSUE TITLE
[Moderation hot fix] Update Content reporting sheet

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#980]
In order to improve our content moderation process we want to simplify the options we provide to users while making it easy for them to understand the implications of their actions. 

Change the content reporting sheet into a two step process:
Step 1: 
Title: Create a content warning for this this post that other users in the network can see
Options: 
- Spam 
- Sexual Content (nudity or pornography) 
- Anti-social behavior (trolling, harassment, or intolderance) 
- Illegal (Content that violates the law in your country or CSAM) 
- Other (items not included above) 
[some sort of next button / indicator]

Step 2: 
Title: Send to Nos or Report Publicly 
whatever content warning the user has selected
Post Publicly | Send to Nos
Include a note to Nos about your report. 
Submit option

**Comment by Chardot** [comment]
[This is a proposal for a super hot fix](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5763%3A12625&mode=design&t=LEwnScaccos6Ue4T-1), which reuses the current reporting UI (context menu). Note that it's not possible to add a text area to let the user attach 
![Screenshot 2024-04-08 at 19 52 53](https://github.com/planetary-social/nos/assets/477835/43eaef56-66c0-4b99-bd98-b9fb3da4db95)
a text note from within the menu.

[This is a proposal for an improved reporting flow](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5763%3A16697&mode=design&t=LEwnScaccos6Ue4T-1), incorporating a text area at the end where the user can add their notes to the content report.
![Screenshot 2024-04-08 at 19 54 57](https://github.com/planetary-social/nos/assets/477835/7df3e746-3469-465a-95d4-309e39d3ac80)
