### ISSUE TITLE
[Ui] Create a pull to refresh element for app

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#983]
Sometimes the Nos app does not auto-load content and / or we want to let users know new content is available bc it has been loading in the background. 

Design an element that encourages users to pull to refresh that can be used on:
- Discover
- Profile 
- Feed

**Comment by Chardot** [comment]
[Here's the design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A24524&mode=design&t=NW5ueLLPC0mGzk55-1) for a pull to refresh element.

[The Pull down to refresh bar](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A25851&mode=design&t=NW5ueLLPC0mGzk55-1) has two states:

- Pulling
- Animation

### Pulling
The bar fades in and grows as the user pulls down

![Image](https://github.com/planetary-social/nos/assets/477835/3fb3dd9a-ce25-4e72-851f-b09df51c1cba)

### Animation
When the user releases the screen, the bar shows an animation to communicate that it's refreshing or fetching new notes from the network.

![Image](https://github.com/planetary-social/nos/assets/477835/2cb8441f-3517-45ff-b174-30e7c5f8bcb1)

### New notes badge
Additionally, I added a [new notes counter badge](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A25966&mode=design&t=NW5ueLLPC0mGzk55-1) that we can display right next to the title of the screen:

When the user taps on the badge, the app will scroll up to the first unread note.
![Image](https://github.com/planetary-social/nos/assets/477835/dd0e347b-9b22-4d22-9fbb-be5f090fa8c6)

**Comment by setch-l** [comment]
@Chardot - I think you missed the story. We need an element that encourages users to pull to refresh. I do not see that in any of these designs. Instead this is animation for what happens when a user takes the action. 

We'll revisit this on Monday

**Comment by Chardot** [comment]
I had initially missed two different things:
• A floating pill that indicates that there are "new notes available" to read
• A button that encourages users to pull down to refresh when they encounter an empty user profile

### [New notes available](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A25966&mode=design&t=924vsspzjnWzKc2a-1)

![Screenshot 2024-04-17 at 20 10 04](https://github.com/planetary-social/nos/assets/477835/4ca5948c-bf4a-4245-b15c-90363bd9a867)

Here's the design in two different versions: 1) the app is able to count the number of new notes available and 2) the app only knows there are new notes available, but it's unable to provide a specific number. Option 2) might be easier to implement in a first iteration.

### [Empty user profile - Pull down to refresh](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A7030&mode=design&t=924vsspzjnWzKc2a-1)

![Screenshot 2024-04-17 at 20 10 12](https://github.com/planetary-social/nos/assets/477835/cb384992-fa0f-4701-bb3e-dd7bbd0279ca)

This button will be added to the empty state of a user profile, inviting users to pull down to refresh.

### [Pulling down to refresh on an empty user profile](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A9391&mode=design&t=924vsspzjnWzKc2a-1)

As the user pulls down to refresh, the progress bar fades in as it grows to a maximum width of 166pt:
![Screenshot 2024-04-17 at 20 45 02](https://github.com/planetary-social/nos/assets/477835/f356e007-21e3-4f39-8b92-37a0d2b78290)

When the user releases the finger, the "searching" animation starts, hiding the button and changing the message to: "Looking for new notes
from this profile..."
![Screenshot 2024-04-17 at 20 28 14](https://github.com/planetary-social/nos/assets/477835/99241b0a-5f7f-4181-9b7f-9049c1e63a23)

**Comment by setch-l** [comment]
@Chardot - Please update the orange New note buttons on the Feed page to Lavendar per the Demo discussion yesterday.

**Comment by Chardot** [comment]
> @Chardot - Please update the orange New note buttons on the Feed page to Lavendar per the Demo discussion yesterday.

I updated the buttons:
![Screenshot 2024-04-22 at 13 17 56](https://github.com/planetary-social/nos/assets/477835/edbb5f2e-6477-446b-b613-832ad7a85656)

[Here's a link to that specific frame on Figma](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A25966&mode=design&t=E4a1Aatu7vNaoKjg-1).
