### ISSUE TITLE
Njump me for nos created NIP05 doesn't work

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#984]
Steps to reproduce:
1. Click on the the following njumpme: 
Latest entries:
1. https://njump.me/petri@nos.social
Pubkey: bc54c2a56ca7b3982c888678c2db79bfaa618b087cb1ee1068815668debed846
Relays: wss://relay.nos.social/
Client IP: 82.131.13.167
User Agent: Nos/222 CFNetwork/1494.0.7 Darwin/23.4.0
Updated At: 2024-03-25T06:32:07.660Z

Issue: get a user not found. 

See slack thread for additional details: https://planetary-app.slack.com/archives/CM4EPK324/p1711461496869119

**Comment by dcadenas** [comment]
I couldn't find any kind 0 in any of the popular relays I looked for so I suspect the app may have crashed during app creation and the user may have entered an inconsistent state as I assume all things that need to be done are not atomic.

**Comment by dcadenas** [comment]
Hmm first time using posthog but it seems that's not the case: https://us.posthog.com/project/56924/person/npub1h32v9ftv57eestygseuv9kmeh74xrzcg0jc7uyrgs9tx3h47mprqg8xq7d#activeTab=events

**Comment by martindsq** [comment]
I looked at the code that publishes a kind 0 event, and it seems to be catching some errors there and silently logging to the log file. I think we should improve the code there and send the error to posthog.

On the other hand, @setch-l do we know that user? To ask him/her to share the logs with us.

**Comment by setch-l** [comment]
We do not - they simply signed up for a NIP05. I just looked them up in Nos and they don't seem to have done anything else in the app.
