### ISSUE TITLE
[Discover tab] Create a Discover tab for show casing Journalists & Creators

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#994]
As a user of Nos
I want an easy way to discover new people to follow both at onboarding and later in my journey
So that my feed is populated with content I want to see. 

AC
- Design a Discover tab that can house both creators and journalists 
- Provide profile info including bio to help people make a decision.

**Comment by Chardot** [comment]
[Here's the design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732%3A4858&mode=design&t=LEwnScaccos6Ue4T-1) for Discover Journalists & Creators.


![Image](https://github.com/planetary-social/nos/assets/477835/e306aa22-47b0-499e-a27e-c65e350dc103)


This design uses the same layout for both categories, adding a filter bar above the scroller. The filter bar will feature [New], [Journalists], and a variety of content creators whose categories are yet to be defined (Tech, Art, video, etc. have been used just as an example here).

Let me know if you need to expose any other detail from Figma.
