### ISSUE TITLE
[Profile Update] Update the profile card header

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#998]
Update the profile card header to support long user names, mostr.pub connections, and removal of followers.

Note this ticket is only for the style updates. It is not for any of the behavior. 

AC 
- long display names elipses out at the end of the line
- users coming from ActivityPub have a mostr.pub label under their NIP05
- Remove followers as a count
- Rearrange the bottom row of the card so it is Follow / Unfollow button | following count | Relays Count 

Designs: 
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5612%3A8318&mode=design&t=SKsJvQIqMHj9dbnv-1

**Comment by martindsq** [comment]
- Remove truncated npub or nip-05 from the Profile title bar and replace it with just "Profile"
- Add borders between Profile Header sections
- Append a (muted) text in the Profile title bar if the profile was muted by the user
- Update follow button: add icons for follow/unfollow actions and let the button grow horizontally to fill available space
- If the user doesn't have a NIP-05, show a truncated npub in secondary color
- Followed by X and Y secondary color, not just primary color
- If the user doesn't have a NIP-05, show the fill npub in secondary color in the Bio Sheet (the one that opens if you tap on the Profile Header elements)
