### ISSUE TITLE
[Profile Update] clicking an extra long display name opens a sheet

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#999]
Given that I am a user of Nos
When I click on an extra long display name
Then a sheet opens with the following info: 

Cancel link in top left
Full Display Name 
NIP05 + mostr.pub icon if needed
Full bio

Designs:
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732%3A8926&mode=design&t=SKsJvQIqMHj9dbnv-1

If the bio is missing open a half sheet: 

Designs:
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5732%3A10504&mode=design&t=SKsJvQIqMHj9dbnv-1

**Comment by martindsq** [comment]
I'm displaying the sheet always in half-screen (the user can still drag the screen to make it full-screen) because I think it's better as most of the time the bio is short enough. Let's see how we experience this and take a decision.
